BuenaVista/urls.py
from django.contrib import admin
from django.contrib.admin.sites import all_sites
from django.urls import path, include
from core import views
from hotel import views as hviews
from venta import views as vviews





urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls', namespace="core")),
    path('hotel/', include('hotel.urls', namespace="hotel")),
    path('venta/', include('venta.urls', namespace="venta")),
    path('', views.home, name="home" ),
]

core/urls.py
from core.views import correctaAdmin, correctaVendedor, localidadModificar, tipoHabitacionModificar
from django.contrib import admin
from django.contrib.admin.sites import all_sites
from django.urls import path, include
from core import views
app_name="core"



urlpatterns = [
  
    path('logout', views.logout, name="logout"),
    path('homeAdministrador', views.correctaAdmin, name="administrador"),
    path('hometaVendedor', views.correctaVendedor,name="vendedor"),
    path('region',views.regionAdmin, name="opcionRegion"),

    path('tipoHabitacion',views.tipoHabitacion, name="opcionTipoHabitacion"),
    path('servicio',views.servicio, name="servicio"),
    path('categoria',views.categoria, name="categoria"),
    path('vendedor', views.vendedor, name='opcionVendedor'),
    path('clienteAdmin', views.cliente, name='cliente'),

    path('crearLocalidad',views.localidadCrear, name="modalCrearLocalidad"),
    path('modificarLocalidad/<ciudad>',views.localidadModificar, name="modalModificarLocalidad"),
    path('crearProvincia',views.provinciaCrear, name="modalCrearProvincia"),
    path('modificarProvincia/<provincia>',views.provinciaModificar, name="modalModificarProvincia"),
    path('crearPais',views.paisCrear, name="modalCrearPais"),
    path('modificarPais/<pais>',views.paisModificar, name="modalModificarPais"),
    path('crearTipoHabitacion',views.tipoHabitacionCrear, name="modalCrearTipoHabitacion"),

    path('modificarTipoHabitacion/<tipoHabitacion>',views.tipoHabitacionModificar, name="modalModificarTipoHabitacion"),
    path('crearServicio',views.servicioCrear, name="modalCrearServicio"),
    path('modificarServicio/<servicio>',views.serviciosModificar, name="modalModificarServicio"),

    path('crearCategoria',views.categoriaCrear, name="modalCrearCategoria"),
    path('modificarCategoria/<categoria>',views.categoriaModificar, name="modalModificarCategoria"),

    path('crearVendedor',views.vendedorCrear, name="modalCrearVendedor"),
    path('modificarVendedor/<vendedor>',views.vendedorModificar, name="modalModificarVendedor"),
    path('eliminarVendedor/<vendedor>', views.vendedorEliminar, name="modalEliminarVendedor"),
    path('reciclarVendedor/<vendedor>', views.vendedorReciclar, name="modalReciclarVendedor"),
    
    path('crearEncargado',views.encargadoCrear, name="modalCrearEncargado"),
    path('modificarEncargado/<encargado>',views.encargadoModificar, name="modalModificarEncargado"),
    path('eliminarEncargado/<encargado>', views.encargadoEliminar, name="modalEliminarEncargado"),
    path('reciclarEncargado/<encargado>', views.encargadoReciclar, name="modalReciclarEncargado"),
    
    path('eliminarCliente/<cliente>', views.clienteEliminar, name="modalEliminarCliente"),
    path('reciclarCliente/<cliente>', views.clienteReciclar, name="modalReciclarCliente"),
    

]

hotel/urls.py
from django.contrib import admin
from django.contrib.admin.sites import all_sites
from django.urls import path, include
from hotel import views as hviews
from core import views as cviews
app_name="hotel"



urlpatterns = [
    path('logout', cviews.logout),

    path('hotel',hviews.hotel, name="hotel"),
    path('crearHotel',hviews.hotelCrear, name="modalCrearHotel"),
    path('modificarHotel/<hotel>',hviews.hotelModificar, name="modalModificarHotel"),

    path('vistaHotel/<hotel>', hviews.detalleHotel, name="vistaHotel"),
    #Path GESTION TIPOHABITACION
    path('tipoHabitacionHotel/<hotel>', hviews.vistaTipoHabitacionHotel, name="tipoHabitacionHotel"),
    path('crearTipoHabitacion/<hotel>', hviews.tipoHabitacionCrear, name="modalCrearTipoHabitacion"), 
    path('modificarTipoHabitacion/<int:hotel>/<int:tipo>)', hviews.tipoHabitacionModificar, name="modalModificarTipoHabitacion"),
    path('eliminarTipoHabitacion/<int:hotel>/<int:tipo>)', hviews.tipoHabitacionEliminar, name="modalEliminarTipoHabitacion"),
    #Path GESTION HABITACION
    path('crearHabitacion/<hotel>', hviews.habitacionCrear, name="modalCrearHabitacion"), 
    path('eliminarHabitacion/<int:hotel>/<int:habitacion>)', hviews.habitacionEliminar, name="modalEliminarHabitacion"),
    path('reciclarHabitacion/<int:hotel>/<int:habitacion>)', hviews.habitacionReciclar, name="modalReciclarHabitacion"),
    #Path GESTION TEMPORADAS
    path('temporadaHotel/<hotel>', hviews.temporadaHotel, name="temporadaHotel"),
    path('crearTemporadaHotel/<hotel>',hviews.temporadaHotelCrear, name="modalCrearTemporadaHotel"),
    path('eliminarTemporada/<int:hotel>/<int:temporada>)', hviews.temporadaEliminar, name="modalEliminarTemporada"),
    path('modificarTemporada/<int:hotel>/<int:temporada>)', hviews.temporadaModificar, name="modalModificarTemporada"),
        
    #Path GESTION PAQUETES TURISTICOS
    path('paqueteTuristicoHotel/<hotel>', hviews.paqueteTuristicoHotel, name="paqueteTuristicoHotel"),
    path('crearPaqueteTuristicoHotel/<hotel>',hviews.paqueteTuristicoHotelCrear, name="modalCrearPaqueteTuristicoHotel"),
    path('modificarPaqueteTuristicoHotel/<int:hotel>/<int:paquete>',hviews.paqueteTuristicoHotelModificar, name="modalModificarPaqueteTuristicoHotel"),
    path('eliminarPaqueteTuristicoHotel/<int:hotel>/<int:paquete>',hviews.paqueteTuristicoHotelEliminar, name="modalEliminarPaqueteTuristicoHotel"),
    
    #Path GESTION SERVICIOS
    path('serviciosHotel/<hotel>', hviews.serviciosHotel, name="serviciosHotel"),
    path('aniadirserviciosHotel/<hotel>',hviews.aniadirServicioHotel, name="modalAniadirserviciosHotel"),
    path('eliminarserviciosHotel/<hotel>/<servicio>',hviews.eliminarServicioHotel, name="modalEliminarserviciosHotel"),
    
    #Path GESTION VENDEDORES HOTEL
    path('vendedoresHotel/<hotel>', hviews.vendedoresHotel, name="vendedoresHotel"),
    path('aniadirVendedorHotel/<hotel>',hviews.aniadirVendedorHotel, name="modalAniadirVendedorHotel"),
    path('eliminarVendedorHotel/<int:hotel>/<int:vendedor>',hviews.vendedorHotelEliminar, name="modalEliminarVendedorHotel"),
]

hotel/views.py
from datetime import date, datetime
from django.contrib.auth.decorators import login_required
from django.db.models import fields
from django.db.models.fields import DateField
from django.forms.widgets import DateInput
from django.shortcuts import render
from typing import Reversible
import django
from django.forms import forms
from django.http import request, JsonResponse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from hotel.helpers import habitacion_duplicada, hay_fechas_superpuestas
from hotel.models import Habitacion, Hotel, PrecioPorTipo, TemporadaAlta, PaqueteTuristico
from .forms import  HabitacionForm, HotelForm, ServicioForm, TemporadaHotelForm, AgregarTipoAHotelForm, HabitacionForm, PaqueteTuristicoForm, VendedorHotelForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate
from django.contrib.auth import login as do_login
from django.contrib.auth import logout
from django.contrib.auth.models import Group, User
from django.utils import timezone
from django.views.generic.edit import CreateView
from core.models import Persona, Vendedor, Categoria, TipoHabitacion, Servicio


# Create your views here.
@login_required
def hotel(request):
    personaInstancia = request.user.persona
    #print(">>>>>>>>>>>>>>>>>>>>>>>>>>>",personaInstancia)
    colHoteles=Hotel.objects.all()
    return render(request, "hotel/hotelAdmin.html",{"colHoteles": colHoteles, "administrador":personaInstancia})

def hotelCrear(request):
    colHoteles = Hotel.objects.all()
    form = HotelForm(request.POST)
    
    if request.method == "POST":
            if form.is_valid():
                hotelInstancia=form.save()
                for servicio in hotelInstancia.categoria.servicios.all():
                    hotelInstancia.servicios.add(servicio)
                hotelInstancia.save()
                return redirect('hotel:hotel')
    return render(request, "hotel/modals/modal_hotel_crear.html", {"colHoteles": colHoteles, "formulario": form})

def hotelModificar(request, hotel):
    hotelInstancia = get_object_or_404(Hotel, pk= hotel )
    colHoteles = Hotel.objects.all()
    if request.method == 'POST':
        form=HotelForm(request.POST,instance=hotelInstancia)
        if form.is_valid():
            hotelInstancia = form.save()
            hotelInstancia.nombre=request.POST['nombre']
            hotelInstancia.direccion=request.POST['direccion']
            hotelInstancia.email=request.POST['email']
            categoria = get_object_or_404( Categoria , pk=request.POST['categoria'])
            
            hotelInstancia.categoria=categoria
            for servicio in hotelInstancia.categoria.servicios.all():
                    hotelInstancia.servicios.add(servicio)
            #hotelInstancia.localidad=request.POST['localidad']
            hotelInstancia.save()
            #form.save_m2m()
            return redirect('hotel:hotel')
        else:
            form=HotelForm(request.POST,instance=hotelInstancia)
    else:
        form=HotelForm(instance=hotelInstancia)
        form.fields['nombre'].widget.attrs['readonly'] = True
        form.fields['localidad'].widget.attrs['style'] = 'display:none;'
        form.fields['localidad'].label = ''
        form.fields['direccion'].widget.attrs['readonly'] = True
        form.fields['encargado'].widget.attrs['style'] = 'display:none;'
        form.fields['encargado'].label = ''
        """
        form.fields['direccion'].widget.attrs['readonly'] = True
        form.fields['encargado'].widget.attrs['readonly'] = True
        """
    return render(request, "hotel/modals/modal_hotel_modificar.html", {"colHoteles": colHoteles, "formulario": form, "hotel": hotelInstancia})


def detalleHotel(request,hotel):
    personaInstancia = request.user.persona
    hotelInstancia =get_object_or_404(Hotel, pk=hotel)  
    return render(request, "hotel/vistaHotelAdmin.html",{"hotel":hotelInstancia,"administrador":personaInstancia})


#-------------------------- INICIO: TIPO DE HABITACION ----------------------------------------

def vistaTipoHabitacionHotel(request,hotel):
    personaInstancia = request.user.persona
    hotelInstancia =get_object_or_404(Hotel, pk=hotel)
    tarifas_hotel=hotelInstancia.tarifario.all()
    return render(request, "hotel/tipoHabitacion_Hotel_Admin.html",{"hotel":hotelInstancia, "tarifas":tarifas_hotel,"administrador":personaInstancia })




def tipoHabitacionCrear(request, hotel):
    hotelInstancia = get_object_or_404(Hotel, pk=hotel)

    if request.method == "POST":
        formulario = AgregarTipoAHotelForm(request.POST)

        if formulario.is_valid():
            precioBaja = formulario.cleaned_data["baja"]
            precioAlta = formulario.cleaned_data["alta"]

            if precioBaja >= 0 and precioAlta >= 0:
                tipoHabitacionRecibido = formulario.save(commit=False)
                tipoHabitacionRecibido.hotel = hotelInstancia
                tipoHabitacionRecibido.save()
                return redirect('hotel:tipoHabitacionHotel', hotel)
        else:
            print("dasdasdasdasdasdasdasdasdasdasdasd")
            print(formulario.errors)
            print("poirtpyoierptyoipretiypoeritp")
            return render(request, "hotel/modals/modal_tipoHabitacionHotel_crear.html", {
                "hotel": hotelInstancia,
                "formulario": formulario,
                "errores": formulario.errors
            })
    else:
        formulario = AgregarTipoAHotelForm()

    return render(request, "hotel/modals/modal_tipoHabitacionHotel_crear.html", {
        "hotel": hotelInstancia,
        "formulario": formulario
    })


def tipoHabitacionModificar(request,hotel,tipo):
    hotelInstancia =get_object_or_404(Hotel, pk=hotel)
    tipoHabitacionInstancia=get_object_or_404(PrecioPorTipo,pk=tipo)
    if request.method == 'POST':
        formulario=AgregarTipoAHotelForm(request.POST,instance=tipoHabitacionInstancia)
        if formulario.is_valid():
            tipoHabitacionInstancia = formulario.save()
            tipoHabitacionInstancia.alta=request.POST['alta']
            tipoHabitacionInstancia.baja=request.POST['baja']
            tipoHabitacionInstancia.save()
            return redirect('hotel:tipoHabitacionHotel', hotel)
        else:
            formulario=AgregarTipoAHotelForm(request.POST,instance=tipoHabitacionInstancia)
    else:
        formulario=AgregarTipoAHotelForm(instance=tipoHabitacionInstancia)
        formulario.fields['tipo'].widget.attrs['style'] = 'display:none;'
        formulario.fields['tipo'].label = ''
    return render(request, "hotel/modals/modal_tipoHabitacionHotel_modificar.html",{"formulario":formulario, "hotel":hotelInstancia ,"tipo":tipoHabitacionInstancia})


def tipoHabitacionEliminar(request,hotel,tipo): 
    hotelInstancia =get_object_or_404(Hotel, pk=hotel)
    tipoHabitacionInstancia=get_object_or_404(PrecioPorTipo,pk=tipo)
    if request.method == 'POST':
        tipoHabitacionInstancia.delete()
        return redirect('hotel:tipoHabitacionHotel', hotel)
    return render(request, "hotel/modals/modal_tipoHabitacionHotel_eliminar.html",{"hotel":hotelInstancia ,"tipo":tipoHabitacionInstancia})
    



#-------------------------- FIN TIPO DE HABITACION ----------------------------------------




#-------------------------- GESTION HABITACIONES ----------------------------------------

def habitacionCrear(request,hotel):
    hotelInstancia =get_object_or_404(Hotel, pk=hotel)
    formulario=HabitacionForm(request.POST)
    if request.method == "POST":
        numero_habitacion_nuevo = request.POST["numero"]
        if formulario.is_valid():
            if not (habitacion_duplicada(numero_habitacion_nuevo , hotel ,formulario)):
                habitacionInstancia=formulario.save(commit=False)
                habitacionInstancia.hotel= hotelInstancia
                habitacionInstancia.save()
                return redirect('hotel:vistaHotel',hotel)
    else:
        formulario=HabitacionForm(request.GET)
        formulario.fields['tipo'].choices=[(t.pk,t.nombre) for t in hotelInstancia.get_tipos()]

    return render(request, "hotel/modals/modal_habitacionHotel_crear.html",{"hotel":hotelInstancia,'formulario':formulario })


def habitacionEliminar(request,hotel,habitacion):
    hotelInstancia =get_object_or_404(Hotel, pk=hotel)
    habitacionInstancia=get_object_or_404(Habitacion,pk=habitacion)
    if request.method == "POST":
        habitacionInstancia.dar_baja()
        habitacionInstancia.save()
        return redirect('hotel:vistaHotel',hotel)
    return render(request, "hotel/modals/modal_habitacionHotel_eliminar.html",{"hotel":hotelInstancia,'habitacion':habitacionInstancia })

def habitacionReciclar(request,hotel,habitacion):
    hotelInstancia =get_object_or_404(Hotel, pk=hotel)
    habitacionInstancia=get_object_or_404(Habitacion,pk=habitacion)
    if request.method == "POST":
        habitacionInstancia.dar_alta()
        habitacionInstancia.save()
        return redirect('hotel:vistaHotel',hotel)
    return render(request, "hotel/modals/modal_habitacionHotel_reciclar.html",{"hotel":hotelInstancia,'habitacion':habitacionInstancia })

#-------------------------- GESTION HABITACIONES ----------------------------------------




#-------------------------- INICIO: GESTION TEMPORADAS ----------------------------------------

def temporadaHotel(request,hotel):
    personaInstancia = request.user.persona
    hotelInstancia =get_object_or_404(Hotel, pk=hotel)    
    return render(request, "hotel/temporada_Hotel_Admin.html",{"hotel":hotelInstancia,"administrador":personaInstancia })


def temporadaHotelCrear(request, hotel):
    form = TemporadaHotelForm(request.POST)
    hotelInstancia=get_object_or_404(Hotel, pk=hotel)
    if request.method == "POST":
            form = TemporadaHotelForm(request.POST)

hotel/templates/hotel/servicios_Hotel_Admin.html
{% extends "hotel/vistaHotelAdmin.html" %}
{% load static %}

{% block header %}
<button onclick="location.href='/core/homeAdministrador'" style="text-decoration:none"
    class="rounded-1 btn  btn-outline-secondary text-white ">Administrador:{% if administrador %}{{administrador.nombre}} {{administrador.apellido}}{% endif %}</button>
{% endblock header %}


{% block datosVista %}

<div class="formularioServicios" id="serviciosHotel">
    <center>
        <h3 class="mb-5">SERVICIOS</h3>
    </center>
    <table id="example1" class="table table-striped table-bordered">
        <button type="button" class="btn btn-success mt-3 mr-4 float-right btn-sm" data-toggle="modal"
            data-target="#aniadirServicio" onclick="abrir_modal('{% url 'hotel:modalAniadirserviciosHotel' hotel.pk %}','#aniadirServicio');">
            <i class="fas fa-plus-circle"></i>
            AÑADIR</button>
        <thead>

            <tr>

                <th>Nombre</th>
                <th>Descripcion</th>
                <th>Referencia</th>
                <th></th>

            </tr>
        </thead>
        <tbody>
            {% for servicio in hotel.get_servicios %}
            <tr>
                <td>{{servicio.nombre}}</td>
                <td>{{servicio.descripcion}}</td>
                <td>{% if servicio in categoria.get_servicios %} CATEGORIA {% else %} EXTRA {% endif %}</td>
                <td>
                    <center>
                        {% if servicio not in categoria.get_servicios %} <button type="button"
                            class="btn btn-danger" data-toggle="modal" data-target="#quitarServicio" onclick="abrir_modal('{% url 'hotel:modalEliminarserviciosHotel' hotel.pk servicio.pk %}','#quitarServicio');"
                            title="Eliminar">
                            <i class="fas fa-trash"></i>
                        </button> {% endif %}


                    </center>
                </td>
            </tr>
            {% endfor %}



        </tbody>

    </table>

    <!--Modal añadir scio Hotel en otro html-->


    <div class="modal fade-scale" id="aniadirServicio" tabindex="-1" aria-labelledby="exampleModalLabel">
    </div>

    <!--Modal eliminar scio en otro html-->

    <div class="modal fade-scale" id="quitarServicio" tabindex="-1" aria-labelledby="exampleModalLabel">
    </div>



</div>

{% endblock datosVista %}


<script type="text/javascript">
    //SCRIPT DE DATATABLE
    const $ = jQuery.noConflict();
    $(document).ready(function () {
        $('#example2').DataTable();
    });</script>

hotel/templates/hotel/temporada_Hotel_Admin.html
{% extends "hotel/vistaHotelAdmin.html" %}
{% load static %}

{% block header %}
<button onclick="location.href='/core/homeAdministrador'" style="text-decoration:none"
    class="rounded-1 btn  btn-outline-secondary text-white ">Administrador:{% if administrador %}{{administrador.nombre}} {{administrador.apellido}}{% endif %}</button>
{% endblock header %}

{% block datosVista %}

<div class="formularioTemporada" id="temporadaHabitaciones">
    <center>
        <h3 class="mb-5">TEMPORADA</h3>
    </center>
    <table id="example1" class="table table-striped table-bordered tablaListaHabitacion">
        <button type="button" class="btn btn-success mt-3 mr-4 float-right btn-sm" data-toggle="modal"
            data-target="#crearTemporadaHotel"
            onclick="abrir_modal('{% url 'hotel:modalCrearTemporadaHotel' hotel.pk %}', '#crearTemporadaHotel');">
            <i class="fas fa-plus-circle"></i>
            AÑADIR</button>
        <thead>

            <tr>

                <th>nombre</th>
                <th>comienza</th>
                <th>finaliza</th>
                <th></th>

            </tr>
        </thead>
        <tbody>

            {% if not hotel.get_temporadas %}
            <td valign="top" colspan="7" class="dataTables_empty"> NO HAY TEMPORADAS CREADAS EN ESTE HOTEL !!!!
            </td>
            {% endif %}
            {% for temporada in hotel.get_temporadas %}


            <tr>

                <td>{{temporada.nombre}}</td>
                <td>{{temporada.inicio}}</td>
                <td>{{temporada.fin}}</td>

                <td>
                    <center>
                        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#modificarTemporada" onclick="abrir_modal('{% url 'hotel:modalModificarTemporada' hotel.pk temporada.pk%}','#modificarTemporada');" title="Modificar">
                            <i class="fas fa-edit"></i>
                        </button>
                        <button type="button" class="btn btn-danger" data-toggle="modal"
                            data-target="#eliminarTemporada"
                            onclick="abrir_modal('{% url 'hotel:modalEliminarTemporada' hotel.pk temporada.pk%}','#eliminarTemporada');" title="Eliminar">
                                <i class="fas fa-trash"></i>
                        </button>
                    </center>
                </td>
            </tr>
            {% endfor %}

        </tbody>

    </table>

    <!--Modal crear temporada Hotel en otro html-->
    

    <div class="modal fade-scale" id="crearTemporadaHotel" tabindex="-1" aria-labelledby="exampleModalLabel">
    </div>

         <!--Modal eliminar Temporada en otro html-->

     <div class="modal fade-scale" id="eliminarTemporada" tabindex="-1" aria-labelledby="exampleModalLabel">
    </div>

       <!--Modal modificar Temporada en otro html-->

       <div class="modal fade-scale" id="modificarTemporada" tabindex="-1" aria-labelledby="exampleModalLabel">
    </div>

</div>

{% endblock datosVista %}


<script type="text/javascript">
    //SCRIPT DE DATATABLE
    const $ = jQuery.noConflict();
    $(document).ready(function () {
        $('#example2').DataTable();
    });</script>

hotel/templates/hotel/tipoHabitacion_Hotel_Admin.html
{% extends "hotel/vistaHotelAdmin.html" %}
{% load static %}

{% block header %}
<button onclick="location.href='/core/homeAdministrador'" style="text-decoration:none"
    class="rounded-1 btn  btn-outline-secondary text-white ">Administrador:{% if administrador %}{{administrador.nombre}} {{administrador.apellido}}{% endif %}</button>
{% endblock header %}

{% block datosVista %}


<div class="formularioHotel" id="vistaTipoHabitaciones">
    <center>
        <h3 class="mb-5" style="margin-top:5vh;">TIPO DE HABITACION CON COSTO POR TEMPORADA</h3>
    </center>
    <table id="example1" class="table table-striped table-bordered tablaListaHabitacion">
        <button type="button" class="btn btn-success mt-3 mr-4 float-right btn-sm" data-toggle="modal"
        data-target="#crearTipoHabitacion" onclick="abrir_modal('{% url 'hotel:modalCrearTipoHabitacion' hotel.pk %}','#crearTipoHabitacion');">
            <i class="fas fa-plus-circle"></i>
            AÑADIR</button>
        <thead>

            <tr>
                <th></th>
                <th>Tipo</th>
                <th>$ Temp. alta</th>
                <th>$ Temp. baja</th>
                <th>Acciones</th>
                <th></th>

            </tr>
        </thead>
        <tbody>

            {% if not hotel.tengo_tipos %}
            <td valign="top" colspan="7" class="dataTables_empty"> NO HAY TIPOS DE HABITACION EN ESTE HOTEL !!!!
            </td>
            {% endif %}



            {% for item in tarifas %}
            <tr>
                <td></td>
                <td>{{item.tipo}}</td>
                <td>${{item.alta}}</td>
                <td>${{item.baja}}</td>
                <td>
                    <center>
                        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#modificarTipoHabitacion" onclick="abrir_modal('{% url 'hotel:modalModificarTipoHabitacion' hotel.pk item.pk %}','#modificarTipoHabitacion');">
                            <i class="fas fa-edit"></i>
                        </button>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#eliminarTipoHabitacion" onclick="abrir_modal('{% url 'hotel:modalEliminarTipoHabitacion' hotel.pk item.pk %}','#eliminarTipoHabitacion');">
                            <i class="fas fa-trash"></i>
                        </button>
                    </center>
                </td>
            </tr>

            {% endfor %}
        </tbody>

    </table>

</div>


 <!--Modal crear Tipo Habitacion en otro html-->

 <div class="modal fade-scale" id="crearTipoHabitacion" tabindex="-1" aria-labelledby="exampleModalLabel">
</div>

<!-- Modal modificar Tipo Habitacion en otro html-->
<div class="modal fade-scale" id="modificarTipoHabitacion" tabindex="-1" aria-labelledby="exampleModalLabel">
</div>

 <!--Modal eliminar Tipo Habitacion en otro html-->

 <div class="modal fade-scale" id="eliminarTipoHabitacion" tabindex="-1" aria-labelledby="exampleModalLabel">
</div>

{% endblock datosVista %}

hotel/templates/hotel/vendedores_Hotel_Admin.html
{% extends "hotel/vistaHotelAdmin.html" %}
{% load static %}
{% block header %}
<button onclick="location.href='/core/homeAdministrador'" style="text-decoration:none"
    class="rounded-1 btn  btn-outline-secondary text-white ">Administrador:{% if administrador %}{{administrador.nombre}} {{administrador.apellido}}{% endif %}</button>
{% endblock header %}


{% block datosVista %}

<div class="formularioVendedor" id="vendedorHotel">
    <center>
        <h3 class="mb-5">VENDEDORES</h3>
    </center>
    <table id="example1" class="table table-striped table-bordered">
        <button type="button" class="btn btn-success mt-3 mr-4 float-right btn-sm" data-toggle="modal"
            data-target="#aniadirVendedor" onclick="abrir_modal('{% url 'hotel:modalAniadirVendedorHotel' hotel.pk %}','#aniadirVendedor');">
            <i class="fas fa-plus-circle"></i>
            AÑADIR</button>
        <thead>

            <tr>

                <th>Nombre</th>
                <th></th>

            </tr>
        </thead>
        <tbody>
            {% for vendedor in hotel.get_vendedores %}
            <tr>
                <td>{{vendedor}}</td>
                <td>
                    <center>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#quitarVendedor"
                            onclick="abrir_modal('{% url 'hotel:modalEliminarVendedorHotel' hotel.pk vendedor.pk %}', '#quitarVendedor');"
                            title="Eliminar">
                            <i class="fas fa-trash"></i>
                        </button>
                    </center>
                </td>
            </tr>
            {% endfor %}



        </tbody>

    </table>

    <!--Modal crear temporada Hotel en otro html-->


    <div class="modal fade-scale" id="aniadirVendedor" tabindex="-1" aria-labelledby="exampleModalLabel">
    </div>

    <!--Modal eliminar Temporada en otro html-->

    <div class="modal fade-scale" id="quitarVendedor" tabindex="-1" aria-labelledby="exampleModalLabel">
    </div>



</div>

{% endblock datosVista %}


<script type="text/javascript">
    //SCRIPT DE DATATABLE
    const $ = jQuery.noConflict();
    $(document).ready(function () {
        $('#example2').DataTable();
    });</script>