BuenaVista/urls.py
from django.contrib import admin
from django.contrib.admin.sites import all_sites
from django.urls import path, include
from core import views
from hotel import views as hviews
from venta import views as vviews





urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls', namespace="core")),
    path('hotel/', include('hotel.urls', namespace="hotel")),
    path('venta/', include('venta.urls', namespace="venta")),
    path('', views.home, name="home" ),
]

core/urls.py
from core.views import correctaAdmin, correctaVendedor, localidadModificar, tipoHabitacionModificar
from django.contrib import admin
from django.contrib.admin.sites import all_sites
from django.urls import path, include
from core import views
app_name="core"



urlpatterns = [
  
    path('logout', views.logout, name="logout"),
    path('homeAdministrador', views.correctaAdmin, name="administrador"),
    path('hometaVendedor', views.correctaVendedor,name="vendedor"),
    path('region',views.regionAdmin, name="opcionRegion"),

    path('tipoHabitacion',views.tipoHabitacion, name="opcionTipoHabitacion"),
    path('servicio',views.servicio, name="servicio"),
    path('categoria',views.categoria, name="categoria"),
    path('vendedor', views.vendedor, name='opcionVendedor'),
    path('clienteAdmin', views.cliente, name='cliente'),

    path('crearLocalidad',views.localidadCrear, name="modalCrearLocalidad"),
    path('modificarLocalidad/<ciudad>',views.localidadModificar, name="modalModificarLocalidad"),
    path('crearProvincia',views.provinciaCrear, name="modalCrearProvincia"),
    path('modificarProvincia/<provincia>',views.provinciaModificar, name="modalModificarProvincia"),
    path('crearPais',views.paisCrear, name="modalCrearPais"),
    path('modificarPais/<pais>',views.paisModificar, name="modalModificarPais"),
    path('crearTipoHabitacion',views.tipoHabitacionCrear, name="modalCrearTipoHabitacion"),

    path('modificarTipoHabitacion/<tipoHabitacion>',views.tipoHabitacionModificar, name="modalModificarTipoHabitacion"),
    path('crearServicio',views.servicioCrear, name="modalCrearServicio"),
    path('modificarServicio/<servicio>',views.serviciosModificar, name="modalModificarServicio"),

    path('crearCategoria',views.categoriaCrear, name="modalCrearCategoria"),
    path('modificarCategoria/<categoria>',views.categoriaModificar, name="modalModificarCategoria"),

    path('crearVendedor',views.vendedorCrear, name="modalCrearVendedor"),
    path('modificarVendedor/<vendedor>',views.vendedorModificar, name="modalModificarVendedor"),
    path('eliminarVendedor/<vendedor>', views.vendedorEliminar, name="modalEliminarVendedor"),
    path('reciclarVendedor/<vendedor>', views.vendedorReciclar, name="modalReciclarVendedor"),
    
    path('crearEncargado',views.encargadoCrear, name="modalCrearEncargado"),
    path('modificarEncargado/<encargado>',views.encargadoModificar, name="modalModificarEncargado"),
    path('eliminarEncargado/<encargado>', views.encargadoEliminar, name="modalEliminarEncargado"),
    path('reciclarEncargado/<encargado>', views.encargadoReciclar, name="modalReciclarEncargado"),
    
    path('eliminarCliente/<cliente>', views.clienteEliminar, name="modalEliminarCliente"),
    path('reciclarCliente/<cliente>', views.clienteReciclar, name="modalReciclarCliente"),
    

]

core/views.py
from typing import Reversible
import django
from django.db.models.enums import Choices
from django.forms import forms
from django.http import request, JsonResponse
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from core.helpers import campo_valido_sin_numeros
from core.models import Pais, Provincia, Localidad, TipoHabitacion, Servicio, Categoria, Persona, Vendedor, Encargado, Cliente
from hotel.models import Hotel
from venta.services import documento_valido
from .forms import PaisForm, LocalidadForm, AutenticacionForm, ProvinciaForm, TipoHabitacionForm, ServicioForm, CategoriaForm, VendedorForm, EncargadoForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate
from django.contrib.auth import login as do_login
from django.contrib.auth import logout as do_logout
from django.contrib.auth.models import Group, User
from django.utils import timezone
from hotel import views as hviews
from venta import views as vviews
import json

from django.views.generic.edit import CreateView


"""def ingresoAdmin(request):
    # Si estamos identificados devolvemos la portada
    if request.user.is_authenticated:
        return render(request, "administrador.html")
    # En otro caso redireccionamos al login
    return redirect('/home.html')"""


def home(request):
    form = AutenticacionForm()
    if request.method == "POST":
        # Añadimos los datos recibidos al formulario
        form = AuthenticationForm(data=request.POST)
        # Si el formulario es válido...
        if form.is_valid():
            # Recuperamos las credenciales validadas
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            # Verificamos las credenciales del usuario
            user = authenticate(username=username, password=password)


            # Si existe un usuario con ese nombre y contraseña
            if user is not None:
                # Hacemos el login manualmente
                do_login(request, user)
                usr = User.objects.get(username=user)
                if usr.groups.filter(name='Administrador').exists():
                    return redirect("core:administrador")
                else:
                    # Y le redireccionamos a la portada
                    return redirect("core:vendedor")
            else:
                return render(request, "home.html", {'form': form})

    # Si llegamos al final renderizamos el formulario
    return render(request, "home.html", {'form': form})


def correctaAdmin(request):
    return redirect("hotel:hotel")


def correctaVendedor(request):
    return redirect("venta:vendedor")


def regionAdmin(request):
    personaInstancia = request.user.persona
    paises = Pais.objects.all()
    provincias = Provincia.objects.all()
    localidades = Localidad.objects.all()
    return render(request, "core/regionAdmin.html", {"paises": paises, "localidades": localidades, "provincias": provincias,"administrador":personaInstancia})


def logout(request):
    if request.user.is_authenticated:
        do_logout(request)
    return redirect(home)
     

def localidadCrear(request):
    # tomo todas las localidades (la idea aca es usarlas para controlar entradas)
    localidades = Localidad.objects.all()
    # variable que toma el formulario con datos que se envia
    formLocalidad = LocalidadForm(request.POST)
    if request.method == "POST":  # si se usa el envio ....
        if formLocalidad.is_valid():  # si es valido el formulario ...
            formLocalidad.save()  # se graba!
            return redirect('core:opcionRegion')  # se redirige hacia region
        else:
            formLocalidad = LocalidadForm(data=request.POST)
            erroresDelFormulario = formLocalidad.errors
            return render(request,  "core/modals/modal_localidad_crear.html", {"localidades": localidades, "formulario": formLocalidad , "errores": erroresDelFormulario})
    # si el metodo es GET se renderiza el modal con un formulario vacio
    return render(request, "core/modals/modal_localidad_crear.html", {"localidades": localidades, "formulario": formLocalidad})


def provinciaCrear(request):
    provincias = Provincia.objects.all()
    formProvincia = ProvinciaForm(request.POST)
    if request.method == 'POST':
        if formProvincia.is_valid():
            formProvincia.save()
            return redirect('core:opcionRegion')
        else:
            formProvincia = ProvinciaForm(data=request.POST)
            erroresDelFormulario = formProvincia.errors
            return render(request, "core/modals/modal_provincia_crear.html", {"provincias": provincias , "formulario": formProvincia , "errores": erroresDelFormulario})
    return render(request, "core/modals/modal_provincia_crear.html", {"provincias": provincias, "formulario": formProvincia})


def paisCrear(request):
    paises = Pais.objects.all()
    formPais = PaisForm(data=request.POST)
    if request.method == "POST":
        if formPais.is_valid():
            formPais.save()
            return redirect('core:opcionRegion')  # se redirige a region
        else:
            formPais = PaisForm(data=request.POST)
            erroresDelFormulario = formPais.errors
            print(erroresDelFormulario)
            return render(request, "core/modals/modal_pais_crear.html", {"paises": paises, "formulario": formPais, "errores": erroresDelFormulario})
    return render(request, "core/modals/modal_pais_crear.html", {"paises": paises, "formulario": formPais})


# se recibe la el objeto ciudad que corresponde a la linea donde se encontraba el boton modificar
def localidadModificar(request, ciudad):
    # ciudadInstancia es el objeto Localidad que corresponde a la ciudad, esto es para modificar lo que ya existe
    ciudadInstancia = get_object_or_404(Localidad, nombre=ciudad)
    # localidades se pretende usar para controlar los ingresos
    localidades = Localidad.objects.all()
    if request.method == 'POST':  # si el metodo es post, esto es el envio de la modificacion
        # el fomulario toma los datos del objeto correspondiente a la ciudad a modificar
        form = LocalidadForm(request.POST, instance=ciudadInstancia)
        if form.is_valid():  # si el formulario es valido
            # tomamos el campo nombre de la instancia que teniamos y la cambiamos por la que nos devuelve el formulario
            ciudadInstancia.nombre = request.POST['nombre']
            ciudadInstancia.save()  # se graba la modificacion
            return redirect('core:opcionRegion')  # se redirige a region
        else:  # si el formulario no fue valido se devuelve para mostrar errores
            form = LocalidadForm(request.POST, instance=ciudadInstancia)
    else:  # si el metodo es GET ...
        form = LocalidadForm(instance=ciudadInstancia)
    return render(request, "core/modals/modal_localidad_modificar.html", {"localidades": localidades, "formulario": form, "ciudad": ciudadInstancia})


def provinciaModificar(request, provincia):
    provinciaInstancia = get_object_or_404(Provincia, nombre=provincia)
    provincias = Provincia.objects.all()
    if request.method == 'POST':
        form = ProvinciaForm(request.POST, instance=provinciaInstancia)
        if form.is_valid():
            provinciaInstancia.nombre = request.POST['nombre']
            provinciaInstancia.save()
            return redirect('core:opcionRegion')
        else:
            form = ProvinciaForm(request.POST, instance=provinciaInstancia)
    else:
        form = ProvinciaForm(instance=provinciaInstancia)
    return render(request, "core/modals/modal_provincia_modificar.html", {"provincias": provincias, "formulario": form, "provincia": provinciaInstancia})


def paisModificar(request, pais):
    paisInstancia = get_object_or_404(Pais, nombre=pais)
    paises = Pais.objects.all()
    if request.method == 'POST':
        form = PaisForm(request.POST, instance=paisInstancia)
        if form.is_valid():
            paisInstancia.nombre = request.POST['nombre']
            paisInstancia.save()
            return redirect('core:opcionRegion')
        else:
            form = PaisForm(request.POST, instance=paisInstancia)
    else:
        form = PaisForm(instance=paisInstancia)
    return render(request, "core/modals/modal_pais_modificar.html", {"paises": paises, "formulario": form, "pais": paisInstancia})


# GESTION TIPO HABITACION


def tipoHabitacion(request):
    personaInstancia = request.user.persona
    tiposHabitaciones = TipoHabitacion.objects.all()
    return render(request, "core/tipoHabitacionAdmin.html", {"tiposHabitaciones": tiposHabitaciones,"administrador":personaInstancia})

def tipoHabitacionCrear(request):
    coltiposHabitaciones = TipoHabitacion.objects.all()
    formTipoHabitacion = TipoHabitacionForm(request.POST)
    if request.method == 'POST':
        if formTipoHabitacion.is_valid():
            formTipoHabitacion.save()
            return redirect('core:opcionTipoHabitacion')
    return render(request, "core/modals/modal_tipoHabitacion_crear.html", {"coltiposHabitaciones": coltiposHabitaciones, "formulario": formTipoHabitacion})


def tipoHabitacionModificar(request, tipoHabitacion):
    tipoHabitacionInstancia = get_object_or_404(
        TipoHabitacion, nombre=tipoHabitacion)
    coltiposHabitaciones = TipoHabitacion.objects.all()
    if request.method == 'POST':
        form = TipoHabitacionForm(
            request.POST, instance=tipoHabitacionInstancia)
        if form.is_valid():
            tipoHabitacionInstancia.nombre = request.POST['nombre']
            tipoHabitacionInstancia.descripcion = request.POST['descripcion']

core/templates/core/modals/modal_categoria_modificar.html
<div class="modal-xl modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title " id="exampleModalLabel">
                MODIFICAR CATEGORIA: NOMBRE: {{categoria.nombre}}
                
            </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form action="{% url 'core:modalModificarCategoria' categoria.nombre %}" method="POST">
        <div class="modal-body">
            Estrellas: 
            <textarea class="mt-2 form-control" style="resize:none" rows="1" readonly="readonly">{{categoria.estrellasStr}}</textarea>
            {% csrf_token %}
            {{ formulario.as_p }}
           
        </div>
        <div class="modal-footer">
            <button type="dismiss" class="Cerrar" data-dismiss="modal">Cerrar</button>
            <button type="submit" name="accion" class="Guardar" value="categoria">Guardar</button>

        </div>
        </form>
    </div>
</div>

core/templates/core/modals/modal_cliente_eliminar.html
<div class="modal-xl modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title " id="exampleModalLabel">
                ELIMINAR CLIENTE: {{cliente.upper}}
                
            </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form action="{% url 'core:modalEliminarCliente' cliente.pk %}" method="POST">
        <div class="modal-body">
            
            {% csrf_token %}
            <p>Seguro que desea eliminar <strong>{{cliente}}</strong>?</p>
            <p>Presione "ACEPTAR" para confirmar!!!!</p>
           
        </div>
        <div class="modal-footer">
            <button type="dismiss" class="Cerrar" data-dismiss="modal">Cerrar</button>
            <button type="submit" name="accion" class="Guardar" value="vendedor">Aceptar</button>

        </div>
        </form>
    </div>
</div>

core/templates/core/modals/modal_encargado_crear.html
{% load static %}

<html>

<head>
    <link rel="icon" type="image/png" href="/static/icons/hotelIco.png">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--SWEET ALERT CSS-->
    <link rel="stylesheet" href="{% static '/css/sweetalert2.css' %}">
    <!--BOOTSTRAP CSS-->
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">

    <!-- Bootstrap CSS para datatable-->
    <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static '/css/dataTables.bootstrap4.min.css' %}">
    <!-- Bootstrap CSS para datatable-->

    <!-- FONTAWESOME -->
    <script src="{% static '/js/d91d4c71ff.js' %}"></script>

    <!--CUSTOM CSS-->
    <link rel="stylesheet" href="{% static '/css/styleBase.css' %}">
    <link rel="stylesheet" href="{% static '/css/modal.css' %}">
    <link rel="stylesheet" href="{% static '/css/botones.css' %}">


    {% block extra_css %}

    {% endblock extra_css %}
</head>

<body class="bodyComplete">


    <!-- HEADER -->
    <div class="container-fluid mainHeader p-3 fixed-top">
        <div class="row">
            <div class="col-2">
                {% block header %}

                {% endblock header %}

            </div>
            <div class="col-8">
                {% block headerContenido %}
                {% endblock headerContenido %}

                {% block carrito %}
                {% endblock carrito %}
            </div>
            <div class="col-2">

                <button onclick="location.href='/core/logout'" style="text-decoration:none; align-items:right;"
                    class="rounded-1 btn btn-lg btn-outline-secondary text-white float-center mt-1  "> Cerrar Sesion
                </button>

            </div>
        </div>
    </div>

    <!-- opciones + contenido -->
    <div class="container-fluid position-fixed" style="top: 100px;">
        <!-- CONTENIDO -->
        <div class="col-12 position-relative "  id="main" >
            <div class="modal-xl modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">
                            CREAR ENCARGADO
                        </h5>
                        <a type="button" class="close" data-dismiss="modal" aria-label="Close" href="{% url 'core:opcionVendedor' %}">
                            <span aria-hidden="true">&times;</span>
                        </a>
                    </div>
                     <form action="{% url 'core:modalCrearEncargado' %}" method="POST">
                        <div class="modal-body" style="max-height: 400px; overflow-y: auto;">
            
                            {% csrf_token %}
                            {{ formulario.as_p }}
                        </div>
                        <div class="modal-footer">
                            <a  href="{% url 'core:opcionVendedor' %}">Cerrar</a>
                            <button type="submit" name="accion" class="Guardar" value="servicio">Guardar</button>
            
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>





    <!-- Footer -->
    <div class="footer text-center mb-0 fixed-bottom">
        <div class="container">
            {% block footer %}

            {% endblock footer %}
            <p class="m-0 mbt1 text-white">&copy; UNPSJB - GRUPO 1 - DESARROLLO DE SOFTWARE</p>
        </div>
    </div>


    <!--sweet alert2-->

    <script src="{% static '/js/sweetalert2@10.js' %}"></script>

    <!-- Bootstrap 4.5-->
    <script src="{% static '/js/jquery-3.5.1.js' %}"></script>
    <script src="{% static '/js/bootstrap.bundle.js' %}"></script>

    <script src="{% static '/js/bootstrap-datetimepicker.min.js' %}"></script>

    <!--dataTable jquery + bootstrap + popper include-->
    <script src="{% static 'js/jquery.dataTables.min.js'%}"></script>
    <script src="{% static '/js/dataTables.bootstrap4.min.js'%}"></script>

    <!--scripts personalizados-->
    <script src="{% static '/js/main.js' %}"></script>

    <!--sweet alert2-->
    <script src="{% static '/js/sweetalert2@10.js' %}"></script>



    <!--dataTable jquery + bootstrap + popper include-->
    <script src="{% static '/js/jquery.dataTables.min.js'%}"></script>
    <script src="{% static '/js/dataTables.bootstrap4.min.js'%}"></script>


    <!--scripts personalizados-->

    <script src="{% static '/js/main.js' %}"></script>

    <!--CUSTOM CSS-->
    <link rel="stylesheet" href="{% static '/css/styleBase.css' %}">
    <link rel="stylesheet" href="{% static '/css/modal.css' %}">
    <link rel="stylesheet" href="{% static '/css/botones.css' %}">

    {% block extrajs %}
    {% endblock %}

</body>


</html>

core/templates/core/modals/modal_encargado_eliminar.html
<div class="modal-xl modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title " id="exampleModalLabel">
                ELIMINAR ENCARGADO: {{encargado.upper}}
                
            </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form action="{% url 'core:modalEliminarEncargado' encargado.pk %}" method="POST">
        <div class="modal-body">
            
            {% csrf_token %}
            <p>Seguro que desea eliminar <strong>{{encargado}}</strong>?</p>
            <p>Presione "ACEPTAR" para confirmar!!!!</p>
           
        </div>
        <div class="modal-footer">
            <button type="dismiss" class="Cerrar" data-dismiss="modal">Cerrar</button>
            <button type="submit" name="accion" class="Guardar" value="vendedor">Aceptar</button>

        </div>
        </form>
    </div>
</div>

core/templates/core/modals/modal_encargado_modificar.html
<div class="modal-xl modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">
                MODIFICAR ENCARGADO: {{encargado.upper}}
            </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span>&times;</span>
            </button>
        </div>
         <form action="{% url 'core:modalModificarEncargado' encargado.pk%}" method="POST">
            <div class="modal-body">

                {% csrf_token %}
                {{ formulario.as_p }}
            </div>
            <div class="modal-footer">
                <button type="dismiss" class="Cerrar" data-dismiss="modal">Cerrar</button>
                <button type="submit" name="accion" class="Guardar" value="servicio">Guardar</button>

            </div>
        </form>
    </div>
</div>

core/templates/core/modals/modal_encargado_reciclar.html
<div class="modal-xl modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title " id="exampleModalLabel">
                RECICLAR ENCARGADO: {{encargado}}
                
            </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form action="{% url 'core:modalReciclarEncargado' encargado.pk %}" method="POST">
        <div class="modal-body">
            
            {% csrf_token %}
            <p>Seguro que desea restaurar de <strong>{{encargado}}</strong></p>
            <p>con numero de documento: <strong>{{encargado.persona.documento}}</strong></p>
            <p>Presione "ACEPTAR" para confirmar!!!!</p>
           
        </div>
        <div class="modal-footer">
            <button type="dismiss" class="Cerrar" data-dismiss="modal">Cerrar</button>
            <button type="submit" name="accion" class="Guardar" value="encargado">Aceptar</button>

        </div>
        </form>
    </div>
</div>

core/templates/core/modals/modal_localidad_modificar.html
<div class="modal-xl modal-dialog modal-dialog-scrollable">
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title " id="exampleModalLabel">
                MODIFICAR LOCALIDAD: {{ciudad}}
            </h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form action="{% url 'core:modalModificarLocalidad' ciudad %}" method="POST">
        <div class="modal-body">

            {% csrf_token %}
            {{ formulario.as_p }}
           
        </div>
        <div class="modal-footer">
            <button type="dismiss" class="Cerrar" data-dismiss="modal">Cerrar</button>
            <button type="submit" name="accion" class="Guardar" value="localidad">Guardar</button>

        </div>
        </form>
    </div>
</div>

core/templates/core/modals/modal_servicio_crear.html
{% load static %}

<html>

<head>
    <link rel="icon" type="image/png" href="/static/icons/hotelIco.png">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--SWEET ALERT CSS-->
    <link rel="stylesheet" href="{% static '/css/sweetalert2.css' %}">
    <!--BOOTSTRAP CSS-->
    <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">

    <!-- Bootstrap CSS para datatable-->
    <link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static '/css/dataTables.bootstrap4.min.css' %}">
    <!-- Bootstrap CSS para datatable-->

    <!-- FONTAWESOME -->
    <script src="{% static '/js/d91d4c71ff.js' %}"></script>

    <!--CUSTOM CSS-->
    <link rel="stylesheet" href="{% static '/css/styleBase.css' %}">
    <link rel="stylesheet" href="{% static '/css/modal.css' %}">
    <link rel="stylesheet" href="{% static '/css/botones.css' %}">


    {% block extra_css %}

    {% endblock extra_css %}
</head>

<body class="bodyComplete">


    <!-- HEADER -->
    <div class="container-fluid mainHeader p-3 fixed-top">
        <div class="row">
            <div class="col-2">
                {% block header %}

                {% endblock header %}

            </div>
            <div class="col-8">
                {% block headerContenido %}
                {% endblock headerContenido %}

                {% block carrito %}
                {% endblock carrito %}
            </div>
            <div class="col-2">

                <button onclick="location.href='/core/logout'" style="text-decoration:none; align-items:right;"
                    class="rounded-1 btn btn-lg btn-outline-secondary text-white float-center mt-1  "> Cerrar Sesion
                </button>

            </div>
        </div>
    </div>

    <!-- opciones + contenido -->
    <div class="container-fluid position-fixed">
        <!-- CONTENIDO -->
        <div class="col-12 position-relative" style="top: 200px;" id="main">

            <div class="modal-xl modal-dialog modal-dialog-scrollable">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">
                            AÑADIR SERVICIO
                        </h5>
                        <a type="button" class="close" data-dismiss="modal" aria-label="Close" href="{% url 'core:servicio' %}">
                            <span aria-hidden="true">&times;</span>
                        </a>
                    </div>
                     <form action="{% url 'core:modalCrearServicio' %}" method="POST">
                        <div class="modal-body">
            
                            {% csrf_token %}
                            {{ formulario.as_p }}
                        </div>
                        <div class="modal-footer">
                            <a  href="{% url 'core:servicio' %}">Cerrar</a>
                            <button type="submit" name="accion" class="Guardar" value="servicio">Guardar</button>
            
                        </div>
                    </form>
                </div>
            </div>
            

        </div>
    </div>


    <!-- Footer -->
    <div class="footer text-center mb-0 fixed-bottom">
        <div class="container">
            {% block footer %}

            {% endblock footer %}
            <p class="m-0 mbt1 text-white">&copy; UNPSJB - GRUPO 1 - DESARROLLO DE SOFTWARE</p>
        </div>
    </div>


    <!--sweet alert2-->

    <script src="{% static '/js/sweetalert2@10.js' %}"></script>

    <!-- Bootstrap 4.5-->
    <script src="{% static '/js/jquery-3.5.1.js' %}"></script>
    <script src="{% static '/js/bootstrap.bundle.js' %}"></script>

    <script src="{% static '/js/bootstrap-datetimepicker.min.js' %}"></script>

    <!--dataTable jquery + bootstrap + popper include-->
    <script src="{% static 'js/jquery.dataTables.min.js'%}"></script>
    <script src="{% static '/js/dataTables.bootstrap4.min.js'%}"></script>

    <!--scripts personalizados-->
    <script src="{% static '/js/main.js' %}"></script>

    <!--sweet alert2-->
    <script src="{% static '/js/sweetalert2@10.js' %}"></script>



    <!--dataTable jquery + bootstrap + popper include-->
    <script src="{% static '/js/jquery.dataTables.min.js'%}"></script>
    <script src="{% static '/js/dataTables.bootstrap4.min.js'%}"></script>


    <!--scripts personalizados-->

    <script src="{% static '/js/main.js' %}"></script>

    <!--CUSTOM CSS-->
    <link rel="stylesheet" href="{% static '/css/styleBase.css' %}">
    <link rel="stylesheet" href="{% static '/css/modal.css' %}">
    <link rel="stylesheet" href="{% static '/css/botones.css' %}">

    {% block extrajs %}
    {% endblock %}

</body>


</html>