BuenaVista/urls.py
from django.contrib import admin
from django.contrib.admin.sites import all_sites
from django.urls import path, include
from core import views
from hotel import views as hviews
from venta import views as vviews





urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls', namespace="core")),
    path('hotel/', include('hotel.urls', namespace="hotel")),
    path('venta/', include('venta.urls', namespace="venta")),
    path('', views.home, name="home" ),
]

core/urls.py
from core.views import correctaAdmin, correctaVendedor, localidadModificar, tipoHabitacionModificar
from django.contrib import admin
from django.contrib.admin.sites import all_sites
from django.urls import path, include
from core import views
app_name="core"



urlpatterns = [
  
    path('logout', views.logout, name="logout"),
    path('homeAdministrador', views.correctaAdmin, name="administrador"),
    path('hometaVendedor', views.correctaVendedor,name="vendedor"),
    path('region',views.regionAdmin, name="opcionRegion"),

    path('tipoHabitacion',views.tipoHabitacion, name="opcionTipoHabitacion"),
    path('servicio',views.servicio, name="servicio"),
    path('categoria',views.categoria, name="categoria"),
    path('vendedor', views.vendedor, name='opcionVendedor'),
    path('clienteAdmin', views.cliente, name='cliente'),

    path('crearLocalidad',views.localidadCrear, name="modalCrearLocalidad"),
    path('modificarLocalidad/<ciudad>',views.localidadModificar, name="modalModificarLocalidad"),
    path('crearProvincia',views.provinciaCrear, name="modalCrearProvincia"),
    path('modificarProvincia/<provincia>',views.provinciaModificar, name="modalModificarProvincia"),
    path('crearPais',views.paisCrear, name="modalCrearPais"),
    path('modificarPais/<pais>',views.paisModificar, name="modalModificarPais"),
    path('crearTipoHabitacion',views.tipoHabitacionCrear, name="modalCrearTipoHabitacion"),

    path('modificarTipoHabitacion/<tipoHabitacion>',views.tipoHabitacionModificar, name="modalModificarTipoHabitacion"),
    path('crearServicio',views.servicioCrear, name="modalCrearServicio"),
    path('modificarServicio/<servicio>',views.serviciosModificar, name="modalModificarServicio"),

    path('crearCategoria',views.categoriaCrear, name="modalCrearCategoria"),
    path('modificarCategoria/<categoria>',views.categoriaModificar, name="modalModificarCategoria"),

    path('crearVendedor',views.vendedorCrear, name="modalCrearVendedor"),
    path('modificarVendedor/<vendedor>',views.vendedorModificar, name="modalModificarVendedor"),
    path('eliminarVendedor/<vendedor>', views.vendedorEliminar, name="modalEliminarVendedor"),
    path('reciclarVendedor/<vendedor>', views.vendedorReciclar, name="modalReciclarVendedor"),
    
    path('crearEncargado',views.encargadoCrear, name="modalCrearEncargado"),
    path('modificarEncargado/<encargado>',views.encargadoModificar, name="modalModificarEncargado"),
    path('eliminarEncargado/<encargado>', views.encargadoEliminar, name="modalEliminarEncargado"),
    path('reciclarEncargado/<encargado>', views.encargadoReciclar, name="modalReciclarEncargado"),
    
    path('eliminarCliente/<cliente>', views.clienteEliminar, name="modalEliminarCliente"),
    path('reciclarCliente/<cliente>', views.clienteReciclar, name="modalReciclarCliente"),
    

]

venta/urls.py
from django.contrib import admin
from django.contrib.admin.sites import all_sites
from django.urls import path, include
from hotel import views as hviews
from core import views as cviews
from venta import views as vviews
app_name="ventas"



urlpatterns = [
    path('logout', cviews.logout),

    path('vendedor',vviews.vendedor, name="vendedor"),
    path('iniciar_venta',vviews.iniciar_venta, name="iniciar_venta"),
    path('buscarHabitaciones/<hotel>', vviews.buscarHabitaciones, name="buscarHabitaciones"),
    path('vistaCliente/', vviews.vista_cliente, name="vistaCliente"),
    path('clienteAniadir/', vviews.cliente_aniadir, name="modalAniadirCliente"),
    path('clienteModificar/<cliente>', vviews.cliente_modificar, name="modalModificarCliente"),
    path('alquilarHabitacion/<habitacion>/<hotel>', vviews.alquilar_habitacion, name="alquilarHabitacion"),
    path('alquilarPaquete/<paquete>/<hotel>', vviews.alquilar_paquete, name="alquilarPaquete"),
    path('vistaCarrito/', vviews.vista_carrito, name="vistaCarrito"),
    path('quitarPaquete/<paquete>', vviews.quitar_paquete_carrito, name="quitarPaqueteCarrito"),
    path('quitarHabitacion/<habitacion>/<desde>/<hasta>', vviews.quitar_habitacion_carrito, name="quitarHabitacionCarrito"),
    path('seleccionarCliente/<cliente>' , vviews.seleccionar_cliente, name="seleccionarCliente"),
    path('facturarCarrito/' , vviews.facturar_carrito, name="facturarCarrito"),
    path('pagarFactura/<factura>' , vviews.pagar_factura, name="pagarFactura"),
    path('cancelarFactura/<factura>' , vviews.cancelar_venta, name="cancelarFactura"),
    path('limpiarPreferencias' , vviews.limpiar_preferencias, name="limpiar_preferencias"),
    path('listado_liquidaciones', vviews.listado_liquidaciones, name="listado_liquidaciones"),
    path('liquidar/<documento>/<fecha_inicio>/<fecha_fin>', vviews.liquidar, name='liquidar'),
    path('listaComprasCliente/<id_cliente>', vviews.lista_compras_cliente, name="listaComprasCliente"),
    ]

core/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from decimal import Decimal
from .utils import str_alfanumerico

# Pais, Provincia, Localidad
class Pais(models.Model):
    nombre = models.CharField(max_length=200, unique=True)

    class Meta:
      verbose_name_plural = "Paises"


    def __str__(self):
        return self.nombre

class Provincia(models.Model):
    nombre = models.CharField(max_length=200 , unique=True)
    pais = models.ForeignKey(Pais, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

class LocalidadManager(models.Manager):
    def crear_zona(self, nombre):
        query = models.Q(nombre__icontains=nombre) | \
            models.Q(provincia__nombre__icontains=nombre) | \
            models.Q(provincia__pais__nombre__icontains=nombre)
        return self.model.objects.filter(query)

class LocalidadQuerySet(models.QuerySet):
    pass

class Localidad(models.Model):
    objects = LocalidadManager.from_queryset(LocalidadQuerySet)()

    nombre = models.CharField(max_length=200)
    provincia = models.ForeignKey(Provincia, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre
    
    class Meta:
        unique_together = (('nombre', 'provincia'), )

# Servicios, Categorias
class Servicio(models.Model):
    nombre = models.CharField(max_length=200 , unique=True)
    descripcion = models.CharField(max_length=800)

    def __str__(self):
        return self.nombre

class Categoria(models.Model):
    ESTRELLA_A = 0
    ESTRELLA_B = 1
    ESTRELLA_C = 2
    ESTRELLA_1 = 3
    ESTRELLA_2 = 4
    ESTRELLA_3 = 5
    ESTRELLA_4 = 6
    ESTRELLA_5 = 7
    ESTRELLAS = (
        (ESTRELLA_A, "A"), 
        (ESTRELLA_B, "B"), 
        (ESTRELLA_C, "C"), 
        (ESTRELLA_1, "Tourist"), 
        (ESTRELLA_2, "Standard"), 
        (ESTRELLA_3, "Comfort"), 
        (ESTRELLA_4, "First Class"), 
        (ESTRELLA_5, "Luxury"), 
    )
   
    estrellas = models.PositiveSmallIntegerField(choices=ESTRELLAS)
    nombre = models.CharField(max_length=200 , unique= True)
    servicios = models.ManyToManyField(Servicio)

    def estrellasStr(self):
        return self.get_estrellas_display()
        
    def __str__(self):
        return self.nombre
    
    def get_servicios(self):
        return Servicio.objects.filter(categoria=self)
    
    

# Tipo De Habitacion
class TipoHabitacion(models.Model):
    nombre = models.CharField(max_length=200 , unique= True)
    descripcion = models.CharField(max_length=800)
    pasajeros = models.PositiveSmallIntegerField()
    # Cuartos para cuando el tipo es Departamento
    cuartos = models.PositiveSmallIntegerField(default = 0)

    def es_departamento(self):
        return self.cuartos == 0

    def __str__(self):
        return self.nombre

class PersonaManager(models.Manager):
    pass

class PersonaQuerySet(models.QuerySet):
    def vendedores(self):
        return self.filter(roles__tipo__exact=Vendedor.TIPO)

    def encargados(self):
        return self.filter(roles__tipo__exact=Encargado.TIPO)

    def clientes(self):
        return self.filter(roles__tipo__exact=Cliente.TIPO)

# Las Personas
class Persona(models.Model):
    DNI = 0
    PASAPORTE = 1
    LIBRETA = 2
    TIPOS_DOCUMENTO = (
        (DNI, "DNI"), 
        (PASAPORTE, "PASAPORTE"), 
        (LIBRETA, "LIBRETA")
    )
    objects = PersonaManager.from_queryset(PersonaQuerySet)()
    tipo_documento = models.PositiveSmallIntegerField(choices=TIPOS_DOCUMENTO)
    documento = models.CharField(max_length=13)
    nombre = models.CharField(max_length=200)
    apellido = models.CharField(max_length=200)
    usuario = models.OneToOneField(User, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f"{self.apellido}, {self.nombre}"

    def como(self, Klass):
        return self.roles.get(tipo=Klass.TIPO).related()

    def agregar_rol(self, rol):
        if not self.sos(rol.__class__):
            rol.persona = self
            rol.save()

    def roles_related(self):
        return [rol.related() for rol in self.roles.all()]

    def sos(self, Klass):
        return any([isinstance(rol, Klass) for rol in self.roles_related()])
    
    def hacer_vendedor(self, user_name, email, password):
        vendedor = Vendedor()
        self.agregar_rol(vendedor)
        self.usuario = User.objects.create_user(user_name, email, password)
        self.usuario.groups.add(Group.objects.get(name="Vendedor"))
        self.save()
        return vendedor
        
    def hacer_encargado(self, clave):
        encargado = Encargado()
        self.agregar_rol(encargado)
        encargado.set_clave(clave)
        self.save()
        return encargado

    def hacer_cliente(self):
        cliente = Cliente()
        self.agregar_rol(cliente)
        self.save()
        return cliente


# Usamos patron roles para
# Encargados, Clientes, Vendedores
class Rol(models.Model):
    TIPO = 0
    TIPOS = [
        (0, "rol")
    ]
    persona = models.ForeignKey(Persona, related_name="roles", on_delete=models.CASCADE)
    tipo = models.PositiveSmallIntegerField(choices=TIPOS)

    def save(self, *args, **kwargs):
        if self.pk is None:
            self.tipo = self.__class__.TIPO
        super(Rol, self).save(*args, **kwargs)

    def related(self):
        return self.__class__ != Rol and self or getattr(self, self.get_tipo_display())

    @classmethod
    def register(cls, klass):
        cls.TIPOS.append((klass.TIPO, klass.__name__.lower()))

    def __str__(self):
        return f"{self.get_tipo_display()} {self.persona}"

class Encargado(Rol):
    TIPO = 1
    bajaEncargado = models.BooleanField(default=False)
    # Clave Autogenerada? un token?
    # clave = models.CharField(max_length=10, default=lambda n = 10: str_alfanumerico(n))
    clave = models.CharField(max_length=10, default="")
    
    def set_clave(self, clave):
        self.clave = clave
        self.save()

    def set_baja(self):
        self.bajaEncargado = True
        self.save()

    def dar_alta(self):
        self.bajaEncargado = False 
        self.save()

class Vendedor(Rol):
    TIPO = 2
    estoyHabilitado = models.BooleanField(default=True) #Baja Logica 
    # Coeficiente de Ganancia
    coeficiente = models.DecimalField(max_digits=3, decimal_places=2, default=Decimal(0))

    def set_baja(self):
        self.estoyHabilitado = False
        self.save()

    def dar_alta(self):
        self.estoyHabilitado = True 
        self.save()
        
class Cliente(Rol):
    TIPO = 3
    bajaCliente = models.BooleanField(default=False) #Baja Logica 
    
    puntos = models.PositiveIntegerField(default=0)

    def set_baja(self):
            self.bajaCliente = True
            self.save()

    def dar_alta(self):
        self.bajaCliente = False
        self.save()

    def agregar_puntos(self, factura):
        puntosFactura= int(factura.total()/5)
        self.puntos+=puntosFactura
        self.save()

    def quitar_puntos(self, factura):
        puntosFactura= int(factura.total())
        self.puntos-=puntosFactura
        self.save()

for Klass in [Encargado, Vendedor, Cliente]:
    Rol.register(Klass)

venta/forms.py
from django.forms import ModelForm, forms, DateInput, DateField, MultipleChoiceField
from django.contrib.auth.forms import AuthenticationForm
from django.forms.fields import CharField, EmailField, IntegerField
from django.forms.widgets import NumberInput
from core.models import Vendedor, Persona, Cliente
from venta.models import Factura




class ClienteForm(ModelForm):
            
    class Meta: 
        model = Persona
        fields = '__all__'
        exclude = [ 'usuario' ]
    
    def __init__(self, *args, **kwargs):
        super(ClienteForm, self).__init__(*args, **kwargs)
        self.fields['nombre'].widget.attrs.update({'class': 'form-control'})   
        self.fields['apellido'].widget.attrs.update({'class': 'form-control'})
        self.fields['documento'].widget.attrs.update({'class': 'form-control'})
        self.fields['tipo_documento'].widget.attrs.update({'class': 'form-control'})

venta/templates/venta/buscarHabitaciones.html
{% extends 'base/vendedor.html'%}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static '/css/vistaHotel.css' %}">
{% endblock extra_css %}

{% block header %}
<button onclick="location.href='/venta/vendedor'" style="text-decoration:none"
    class="rounded-1 btn btn-sm btn-outline-secondary text-white ml-4 mt-1"> VENDEDOR: {{vendedor.persona.nombre.upper}}
    {{vendedor.persona.apellido.upper}} </button>
{% endblock header %}

{% block carritoz %}

{%block carrito_contador %} {%if not contador%}0{% else %}{{contador}} {% endif %}{% endblock carrito_contador%}
{% endblock carritoz %}
<script type="text/javascript">
    //SCRIPT DE DATATABLE
    const $ = jQuery.noConflict();
    $(document).ready(function () {
        $('#example1').DataTable();
        $('#example2').DataTable();
    });
</script>

{% block content %}



<!--  #######################  DATOS DEL HOTEL  #######################-->

<div class="titulo">
    <h1>
        <center> <u> {%if hotel.es_hospedaje%} HOSPEDAJE {%else%} HOTEL {% endif %} {{hotel.nombre.upper}}</u> </center>
    </h1>
</div>
<div class="datosHotel">
    <div class="container">
        <div class="row">
            <div class="col-sm-3 lugarImagen">
                <img class="imagen" src="{% static '/media/hoteles/1.jpg' %}">
            </div>
            <div class="col-sm-7">
                <center>
                    <table class="table table-responsive tablaDatos">
                        <tr>
                            <th>Direccion:</th>
                            <td>{{hotel.direccion}}</td>
                        </tr>
                        <tr>
                            <th>E-mail:</th>
                            <td>{{hotel.email}}</td>
                        </tr>
                        <tr>
                            <th>Telefono:</th>
                            <td>{{hotel.telefono}}</td>
                        </tr>
                        <tr>
                            <th>Localidad:</th>
                            <td>{{hotel.localidad}}</td>
                        </tr>
                        <tr>
                            <th>Categoria:</th>
                            <td>{{hotel.categoria}}</td>
                        </tr>
                    </table>
                </center>

            </div>

        </div>
    </div>
    <div class="modal fade-scale" id="modificarHotel" tabindex="-1" aria-labelledby="exampleModalLabel">
    </div>
</div>

<!--  ####################### FIN DATOS DEL HOTEL  #######################-->


<!--  #######################  TABLA LISTADO HABITACIONES/PAQUETES  #######################-->

<!--  #######################  BOTON DE CAMBIO LISTADO HABITACIONES/PAQUETES  #######################-->
{% block datosVista %}
<div class="abajo">

    <div id="container">
        <input class="boton-Habitaciones-Paquetes" type="radio" id="habitaciones" name="material" value="habitaciones">
        <label class="etiqueta-boton" for="habitaciones" id="label-1" onclick='seleccionarEstado("habitaciones")'>
            <span class="glyphicon glyphicon-user"><i class="fas fa-bed"></i></span></label>
        <input class="boton-Habitaciones-Paquetes" type="radio" id="paquetes" name="material" value="paquetes">
        <label class="etiqueta-boton" for="paquetes" id="label-2" onclick='seleccionarEstado("paquetes")'>
            <span class="glyphicon glyphicon-bell"><i class=" fas fa-box"></i></span></label>
   
        <div id="effect"></div>
    </div>

    <!--  #######################  FIN BOTON DE CAMBIO LISTADO HABITACIONES/PAQUETES  #######################-->

    <!--  #######################  INICIO DATA TABLE LISTADO HABITACIONES/PAQUETES  #######################-->

    <div class="formularioHotel1" id="vistaHabitaciones">
        <center>
            <h1 class="my-4">LISTADO DE HABITACIONES DISPONIBLES</h1>
        </center>
        <table id="example1" class="table table-striped table-bordered tablaListaHabitacion">
            <thead>

                <tr>
                    <th></th>
                    <th>Tipo</th>
                    <th>Numero</th>
                    <th>Capacidad</th>
                    <th>Precio</th>
                    <th>Acciones</th>
                </tr>
            </thead>
            <tbody>

                {% if not habitaciones_disponibles %}
                <td valign="top" colspan="7" class="dataTables_empty"> NO HAY HABITACIONES DISPONIBLES !!!!
                </td>
                {% endif %}
                {% for habitacion in habitaciones_disponibles %}
                <tr>
                    <td></td>
                    <td>{{habitacion.tipo}}</td>
                    <td>{{habitacion.numero}}</td>
                    <td>{{habitacion.tipo.pasajeros}}</td>
                    <td>${{habitacion.precio}}</td>
                    <td>
                        <center>
                            <button type="button" class="btn btn-success"
                                onclick=location.href="{% url 'venta:alquilarHabitacion' habitacion.id hotel.pk %}"
                                title="Alquilar">
                                <i class="fas fa-shopping-cart"></i> </button>
                        </center>
                    </td>
                </tr>
                {% endfor %}

            </tbody>

        </table>

    </div>




    <div class="formularioHotel2" id="vistaPaquetes">
        <center>
            <h1 class="my-4">LISTADO DE PAQUETES DISPONIBLES</h1>
        </center>
        <table id="example2" class="table table-striped table-bordered tablaListaHabitacion">

            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Fecha inicio</th>
                    <th>Fecha fin</th>
                    <th>Costo</th>
                    <th>Pasajeros</th>
                    <th>Habitaciones</th>
                    <th>Acciones</th>
                </tr>

            </thead>
            <tbody>

                {% if not paquetes_disponibles %}
                <td valign="top" colspan="7" class="dataTables_empty text-center"> NO HAY PAQUETES CREADOS EN ESTE HOTEL
                    !!!!
                </td>
                {% endif %}
                {% for paquete in paquetes_disponibles %}

                <tr>
                    <td>{{paquete.nombre}}</td>
                    <td>{{paquete.inicio}}</td>
                    <td>{{paquete.fin}}</td>
                    <td>${{paquete.get_costo}}</td>
                    <td>{{paquete.get_pasajeros}}</td>
                    <td> {% for habitacion in paquete.get_habitaciones %}
                        <p>habitacion: {{habitacion.numero}} tipo: {{habitacion.tipo}}</p>
                        {% endfor %}
                    </td>
                    <td>
                        <center>
                            <button type="button" class="btn btn-success"
                            onclick=location.href="{% url 'venta:alquilarPaquete' paquete.pk hotel.pk %}"
                            title="Alquilar">
                            <i class="fas fa-shopping-cart"></i> </button>
                        </center>
                    </td>
                </tr>
                {% endfor %}

            </tbody>

        </table>

    </div>

    {% endblock datosVista %}
    {% endblock content %}

    {% block extrajs %}


    <script>
        let state = sessionStorage.getItem("eleccion") || "habitaciones";
        document.getElementById(state).setAttribute("checked" , "")
        mostrarListado(state)
        
        function seleccionarEstado(estado){
            sessionStorage.setItem("eleccion" , estado)
            document.getElementById(estado).setAttribute("checked" , "")
            mostrarListado(estado)
        }
    
    
        function mostrarListado(state){
            switch (state) {
                case "habitaciones":
                    document.getElementById("vistaPaquetes").style.display = "none";
                    document.getElementById("vistaHabitaciones").style.display = "block";
                    break;
                case "paquetes":
                    document.getElementById("vistaPaquetes").style.display = "block";
                    document.getElementById("vistaHabitaciones").style.display = "none";
                    break;
            }
        }
    </script>
    <script src="{% static 'js/dd8c49730d.js' %}"></script>#


    {% endblock extrajs%}

venta/templates/venta/carrito.html
{% extends 'base/vendedor.html'%}
{% load static %}

{% block header %}
<button onclick="location.href='/venta/vendedor'" style="text-decoration:none"
    class="rounded-1 btn btn-sm btn-outline-secondary text-white ml-4 mt-1"> VENDEDOR: {{vendedor.persona.nombre.upper}}
    {{vendedor.persona.apellido.upper}} </button>
{% endblock header %}

{% block carrito %}
<!--VACIO PARA QUE NO APAREZCA EL CARRITO, DADO QUE ESTAMOS EN LA VISTA CARRITO-->
{% endblock carrito %}


{% block content %}
{% if not contador %}
<br><br><br><br><br>
<center>
    <h1 class="mt-5" style="color:#666;">Tu carrito está vacío</h1>
</center>
<center>
    <h5 style="color:#666;">¿No sabés qué comprar? ¡Miles de habitaciones y paquetes te esperan! </h5>
</center>
{%else%}

<div class="formularioCarrito" id="vistaCarrito">
    <center>
        <h1 class="my-4">LISTADO ITEMS CARRITO</h1>
    </center>
    <table id="example1" class="table table-striped table-bordered tablaListaHabitacion">

        <thead>
            <tr>
                <th><center>Hotel</center></th>
                <th><center>Descripcion</center></th>
                <!--CASO HAB HABITACION N°: , CASO PAQ PAQUETE: NOMBRE-->
                <th><center>Fecha inicio</center></th>
                <th><center>Fecha fin</center></th>
                <th><center>Costo Unitario</center></th>
                <!--CASO HAB COSTO POR NOCHE , CASO PAQ COSTO SUBTOTAL REPETIDO-->
                <th><center>SubTotal</center></th>
                <th><center>Quitar</center></th>
            </tr>

        </thead>
        <tbody>
            {% for key,value in coleccion_ventas.items%}
            {% if "total" not in key%}
            <tr>

                <td>{{value.hotel}}</td>
                <td>{{value.descripcion}}</td>
                <td>{{value.fecha_inicio}}</td>
                <td>{{value.fecha_fin}}</td>
                <td>{{value.costo_unitario}}</td>
                <td>{{value.subtotal}}</td>

                <td>
                    <center>

                        <button type="button" class="btn btn-danger" {% if "p" in key %} onclick="location.href='{% url 'venta:quitarPaqueteCarrito' key %}' " {% else %} onclick="location.href='{% url 'venta:quitarHabitacionCarrito' key value.fecha_inicio value.fecha_fin %}' "{% endif %} title="Eliminar">
                            <i class="fas fa-trash"></i>
                        </button>

                    </center>
                </td>
            </tr>
            {%endif%}
            {% endfor %}

        </tbody>

    </table>
    <div class="row mt-2">
        <div class="col-10 ml-4" style="background-color:rgb(185, 182, 182);"> <h3>TOTAL: ${{total}}</h3></div>
        <div class="col-1"><button class="btn btn-success" {% if cliente is None %} onclick="Swal.fire({
            icon: 'error',
            title: 'No se puede facturar sin seleccionar un Cliente',
            text: 'Ingrese a menu cliente y seleccione uno...',
        });" {% else %} onClick="location.href='{% url 'venta:facturarCarrito' %}'" {% endif %}>FACTURAR</button> </div>
    </div>
    

</div>

{% endif %}



{% endblock content %}

{% block extrajs %}


<script type="text/javascript">
    //SCRIPT DE DATATABLE
    const $ = jQuery.noConflict();
    $(document).ready(function () {
        $('#example1').DataTable();
    });
</script>


{% endblock extrajs %}

venta/templates/venta/vista_cliente.html
{% extends 'base/vendedor.html'%} {% load static %}  {% block header %}
<button onclick="location.href='/venta/vendedor'" style="text-decoration:none" class="rounded-1 btn btn-sm btn-outline-secondary text-white ml-4 mt-1"> VENDEDOR: {{vendedor.persona.nombre.upper}}
    {{vendedor.persona.apellido.upper}} </button> {% endblock header %} {% block carritoz %} {%block carrito_contador %} {%if not contador%}0{% else %}{{contador}} {% endif %}{% endblock carrito_contador%} {% endblock carritoz %} {% block content %}

<center>
    <h1 class="my-4">LISTADO DE CLIENTES</h1>
</center>


<!-- VISTA CLIENTES -->

<table id="example1" class="table table-striped table-bordered" style="width:100%">

    <div class="formularioCliente" id="vistaClientes">


        <thead>

            <tr>
                <button type="button" class="btn btn-success  mr-4 float-right btn-sm" data-toggle="modal" data-target="#aniadirCliente" onclick="abrir_modal('{% url 'venta:modalAniadirCliente' %}','#aniadirCliente');">
                    <i class="fas fa-plus-circle"></i>
                    AÑADIR</button>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Tipo</th>
                <th>Nro de Documento</th>
                <th>Puntos</th>
                <th>
                    <Center>Modificar</Center>
                </th>
                <th>
                    <Center>Seleccionar</Center>
                </th>
                <th>
                    <Center>lista compras realizadas</Center>
                </th>
            </tr>
        </thead>
        <tbody>


            {% for cliente in colClientes %} {% if not cliente.bajaCliente %}
            <tr>

                <td> {{cliente.persona.nombre}}</td>
                <td> {{cliente.persona.apellido}}</td>
                <td> {{cliente.persona.get_tipo_documento_display}}</td>
                <td> {{cliente.persona.documento}}</td>
                <td> {{cliente.puntos}}</td>

                <td>
                    <center>

                        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#modificarCliente" onclick="abrir_modal('{% url 'venta:modalModificarCliente' cliente.pk  %}','#modificarCliente');" title="Editar">
                            <i class="fas fa-edit"></i>
                        </button>


                    </center>

                </td>
                <td>
                    <center>

                        <button type="button" class="btn btn-success" onclick="location.href='{% url 'venta:seleccionarCliente' cliente.persona.id %}' " title="Seleccionar">
                            <i class="fas fa-check-square"></i>
                        </button>


                    </center>

                </td>
                <td>
                    <center>

                        <button type="button" class="btn btn-success" onclick="location.href='{% url 'venta:listaComprasCliente' cliente.pk %}' ">
                            <i class="fas fa-check-square"></i>
                        </button>


                    </center>

                </td>

            </tr>
            {% endif %} {% endfor %}

        </tbody>

</table>
<!--Modales en otro html-->

<div class="modal fade-scale" id="modificarCliente" tabindex="-1" aria-labelledby="exampleModalLabel">
</div>

<div class="modal fade-scale" id="aniadirCliente" tabindex="-1" aria-labelledby="exampleModalLabel">
</div>

</div>

{% endblock content %} {% block extrajs %}

<script type="text/javascript">
    //SCRIPT DE DATATABLE
    const $ = jQuery.noConflict();
    $(document).ready(function() {
        $('#example1').DataTable();
    });
</script>


{% endblock extrajs%}