BuenaVista/urls.py
from django.contrib import admin
from django.contrib.admin.sites import all_sites
from django.urls import path, include
from core import views
from hotel import views as hviews
from venta import views as vviews





urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls', namespace="core")),
    path('hotel/', include('hotel.urls', namespace="hotel")),
    path('venta/', include('venta.urls', namespace="venta")),
    path('', views.home, name="home" ),
]

core/urls.py
from core.views import correctaAdmin, correctaVendedor, localidadModificar, tipoHabitacionModificar
from django.contrib import admin
from django.contrib.admin.sites import all_sites
from django.urls import path, include
from core import views
app_name="core"



urlpatterns = [
  
    path('logout', views.logout, name="logout"),
    path('homeAdministrador', views.correctaAdmin, name="administrador"),
    path('hometaVendedor', views.correctaVendedor,name="vendedor"),
    path('region',views.regionAdmin, name="opcionRegion"),

    path('tipoHabitacion',views.tipoHabitacion, name="opcionTipoHabitacion"),
    path('servicio',views.servicio, name="servicio"),
    path('categoria',views.categoria, name="categoria"),
    path('vendedor', views.vendedor, name='opcionVendedor'),
    path('clienteAdmin', views.cliente, name='cliente'),

    path('crearLocalidad',views.localidadCrear, name="modalCrearLocalidad"),
    path('modificarLocalidad/<ciudad>',views.localidadModificar, name="modalModificarLocalidad"),
    path('crearProvincia',views.provinciaCrear, name="modalCrearProvincia"),
    path('modificarProvincia/<provincia>',views.provinciaModificar, name="modalModificarProvincia"),
    path('crearPais',views.paisCrear, name="modalCrearPais"),
    path('modificarPais/<pais>',views.paisModificar, name="modalModificarPais"),
    path('crearTipoHabitacion',views.tipoHabitacionCrear, name="modalCrearTipoHabitacion"),

    path('modificarTipoHabitacion/<tipoHabitacion>',views.tipoHabitacionModificar, name="modalModificarTipoHabitacion"),
    path('crearServicio',views.servicioCrear, name="modalCrearServicio"),
    path('modificarServicio/<servicio>',views.serviciosModificar, name="modalModificarServicio"),

    path('crearCategoria',views.categoriaCrear, name="modalCrearCategoria"),
    path('modificarCategoria/<categoria>',views.categoriaModificar, name="modalModificarCategoria"),

    path('crearVendedor',views.vendedorCrear, name="modalCrearVendedor"),
    path('modificarVendedor/<vendedor>',views.vendedorModificar, name="modalModificarVendedor"),
    path('eliminarVendedor/<vendedor>', views.vendedorEliminar, name="modalEliminarVendedor"),
    path('reciclarVendedor/<vendedor>', views.vendedorReciclar, name="modalReciclarVendedor"),
    
    path('crearEncargado',views.encargadoCrear, name="modalCrearEncargado"),
    path('modificarEncargado/<encargado>',views.encargadoModificar, name="modalModificarEncargado"),
    path('eliminarEncargado/<encargado>', views.encargadoEliminar, name="modalEliminarEncargado"),
    path('reciclarEncargado/<encargado>', views.encargadoReciclar, name="modalReciclarEncargado"),
    
    path('eliminarCliente/<cliente>', views.clienteEliminar, name="modalEliminarCliente"),
    path('reciclarCliente/<cliente>', views.clienteReciclar, name="modalReciclarCliente"),
    

]

core/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from decimal import Decimal
from .utils import str_alfanumerico

# Pais, Provincia, Localidad
class Pais(models.Model):
    nombre = models.CharField(max_length=200, unique=True)

    class Meta:
      verbose_name_plural = "Paises"


    def __str__(self):
        return self.nombre

class Provincia(models.Model):
    nombre = models.CharField(max_length=200 , unique=True)
    pais = models.ForeignKey(Pais, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre

class LocalidadManager(models.Manager):
    def crear_zona(self, nombre):
        query = models.Q(nombre__icontains=nombre) | \
            models.Q(provincia__nombre__icontains=nombre) | \
            models.Q(provincia__pais__nombre__icontains=nombre)
        return self.model.objects.filter(query)

class LocalidadQuerySet(models.QuerySet):
    pass

class Localidad(models.Model):
    objects = LocalidadManager.from_queryset(LocalidadQuerySet)()

    nombre = models.CharField(max_length=200)
    provincia = models.ForeignKey(Provincia, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre
    
    class Meta:
        unique_together = (('nombre', 'provincia'), )

# Servicios, Categorias
class Servicio(models.Model):
    nombre = models.CharField(max_length=200 , unique=True)
    descripcion = models.CharField(max_length=800)

    def __str__(self):
        return self.nombre

class Categoria(models.Model):
    ESTRELLA_A = 0
    ESTRELLA_B = 1
    ESTRELLA_C = 2
    ESTRELLA_1 = 3
    ESTRELLA_2 = 4
    ESTRELLA_3 = 5
    ESTRELLA_4 = 6
    ESTRELLA_5 = 7
    ESTRELLAS = (
        (ESTRELLA_A, "A"), 
        (ESTRELLA_B, "B"), 
        (ESTRELLA_C, "C"), 
        (ESTRELLA_1, "Tourist"), 
        (ESTRELLA_2, "Standard"), 
        (ESTRELLA_3, "Comfort"), 
        (ESTRELLA_4, "First Class"), 
        (ESTRELLA_5, "Luxury"), 
    )
   
    estrellas = models.PositiveSmallIntegerField(choices=ESTRELLAS)
    nombre = models.CharField(max_length=200 , unique= True)
    servicios = models.ManyToManyField(Servicio)

    def estrellasStr(self):
        return self.get_estrellas_display()
        
    def __str__(self):
        return self.nombre
    
    def get_servicios(self):
        return Servicio.objects.filter(categoria=self)
    
    

# Tipo De Habitacion
class TipoHabitacion(models.Model):
    nombre = models.CharField(max_length=200 , unique= True)
    descripcion = models.CharField(max_length=800)
    pasajeros = models.PositiveSmallIntegerField()
    # Cuartos para cuando el tipo es Departamento
    cuartos = models.PositiveSmallIntegerField(default = 0)

    def es_departamento(self):
        return self.cuartos == 0

    def __str__(self):
        return self.nombre

class PersonaManager(models.Manager):
    pass

class PersonaQuerySet(models.QuerySet):
    def vendedores(self):
        return self.filter(roles__tipo__exact=Vendedor.TIPO)

    def encargados(self):
        return self.filter(roles__tipo__exact=Encargado.TIPO)

    def clientes(self):
        return self.filter(roles__tipo__exact=Cliente.TIPO)

# Las Personas
class Persona(models.Model):
    DNI = 0
    PASAPORTE = 1
    LIBRETA = 2
    TIPOS_DOCUMENTO = (
        (DNI, "DNI"), 
        (PASAPORTE, "PASAPORTE"), 
        (LIBRETA, "LIBRETA")
    )
    objects = PersonaManager.from_queryset(PersonaQuerySet)()
    tipo_documento = models.PositiveSmallIntegerField(choices=TIPOS_DOCUMENTO)
    documento = models.CharField(max_length=13)
    nombre = models.CharField(max_length=200)
    apellido = models.CharField(max_length=200)
    usuario = models.OneToOneField(User, null=True, blank=True, on_delete=models.SET_NULL)

    def __str__(self):
        return f"{self.apellido}, {self.nombre}"

    def como(self, Klass):
        return self.roles.get(tipo=Klass.TIPO).related()

    def agregar_rol(self, rol):
        if not self.sos(rol.__class__):
            rol.persona = self
            rol.save()

    def roles_related(self):
        return [rol.related() for rol in self.roles.all()]

    def sos(self, Klass):
        return any([isinstance(rol, Klass) for rol in self.roles_related()])
    
    def hacer_vendedor(self, user_name, email, password):
        vendedor = Vendedor()
        self.agregar_rol(vendedor)
        self.usuario = User.objects.create_user(user_name, email, password)
        self.usuario.groups.add(Group.objects.get(name="Vendedor"))
        self.save()
        return vendedor
        
    def hacer_encargado(self, clave):
        encargado = Encargado()
        self.agregar_rol(encargado)
        encargado.set_clave(clave)
        self.save()
        return encargado

    def hacer_cliente(self):
        cliente = Cliente()
        self.agregar_rol(cliente)
        self.save()
        return cliente


# Usamos patron roles para
# Encargados, Clientes, Vendedores
class Rol(models.Model):
    TIPO = 0
    TIPOS = [
        (0, "rol")
    ]
    persona = models.ForeignKey(Persona, related_name="roles", on_delete=models.CASCADE)
    tipo = models.PositiveSmallIntegerField(choices=TIPOS)

    def save(self, *args, **kwargs):
        if self.pk is None:
            self.tipo = self.__class__.TIPO
        super(Rol, self).save(*args, **kwargs)

    def related(self):
        return self.__class__ != Rol and self or getattr(self, self.get_tipo_display())

    @classmethod
    def register(cls, klass):
        cls.TIPOS.append((klass.TIPO, klass.__name__.lower()))

    def __str__(self):
        return f"{self.get_tipo_display()} {self.persona}"

class Encargado(Rol):
    TIPO = 1
    bajaEncargado = models.BooleanField(default=False)
    # Clave Autogenerada? un token?
    # clave = models.CharField(max_length=10, default=lambda n = 10: str_alfanumerico(n))
    clave = models.CharField(max_length=10, default="")
    
    def set_clave(self, clave):
        self.clave = clave
        self.save()

    def set_baja(self):
        self.bajaEncargado = True
        self.save()

    def dar_alta(self):
        self.bajaEncargado = False 
        self.save()

class Vendedor(Rol):
    TIPO = 2
    estoyHabilitado = models.BooleanField(default=True) #Baja Logica 
    # Coeficiente de Ganancia
    coeficiente = models.DecimalField(max_digits=3, decimal_places=2, default=Decimal(0))

    def set_baja(self):
        self.estoyHabilitado = False
        self.save()

    def dar_alta(self):
        self.estoyHabilitado = True 
        self.save()
        
class Cliente(Rol):
    TIPO = 3
    bajaCliente = models.BooleanField(default=False) #Baja Logica 
    
    puntos = models.PositiveIntegerField(default=0)

    def set_baja(self):
            self.bajaCliente = True
            self.save()

    def dar_alta(self):
        self.bajaCliente = False
        self.save()

    def agregar_puntos(self, factura):
        puntosFactura= int(factura.total()/5)
        self.puntos+=puntosFactura
        self.save()

    def quitar_puntos(self, factura):
        puntosFactura= int(factura.total())
        self.puntos-=puntosFactura
        self.save()

for Klass in [Encargado, Vendedor, Cliente]:
    Rol.register(Klass)

core/forms.py
from django.forms import ModelForm,MultipleChoiceField, CheckboxSelectMultiple, forms, ValidationError
from django.forms import widgets, MultipleChoiceField, CheckboxSelectMultiple
from core.models import Localidad, Pais, Provincia, Persona, TipoHabitacion, Servicio, Categoria, Vendedor, Encargado
from django.contrib.auth.forms import AuthenticationForm
from django.forms.fields import CharField, EmailField

# 
class PaisForm(ModelForm):
    class Meta:
        model = Pais
        fields = ['nombre']
   
    
    def __init__(self, *args, **kwargs):
        super(PaisForm, self).__init__(*args, **kwargs)
        self.fields['nombre'].widget.attrs.update({'class': 'form-control', 'placeholder':'Ingrese Nombre Pais', 'title':'Ingrese mas de tres caracteres, no deje en blanco'})

    def clean_nombre(self):
         nombreRecibido = self.cleaned_data.get("nombre")
         if nombreRecibido == '':
           raise ValidationError('Este nombre no esta permitido')
         if nombreRecibido.split(' ') == ' ':
           raise ValidationError('El nombre no puede estar vacio')
         return nombreRecibido
   
        

class ProvinciaForm(ModelForm):
    class Meta:
        model = Provincia
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProvinciaForm, self).__init__(*args, **kwargs)
        self.fields['nombre'].widget.attrs.update({'class': 'form-control'})


class LocalidadForm(ModelForm):
    class Meta:
        model = Localidad
        fields = '__all__'
        

    def __init__(self, *args, **kwargs):
        super(LocalidadForm, self).__init__(*args, **kwargs)
        self.fields['nombre'].widget.attrs.update({'class': 'form-control'})
        

class AutenticacionForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super(AutenticacionForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Ingrese su usuario'})
        self.fields['password'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Ingrese su Clave'})
        self.fields['username'].label = ''
        self.fields['password'].label = ''

class TipoHabitacionForm(ModelForm):
    class Meta:
        model=TipoHabitacion
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        super(TipoHabitacionForm, self).__init__(*args, **kwargs)
        self.fields['nombre'].widget.attrs.update({'class': 'form-control'})   
        self.fields['descripcion'].widget.attrs.update({'class': 'form-control'})
        self.fields['pasajeros'].widget.attrs.update({'class': 'form-control'})
        self.fields['cuartos'].widget.attrs.update({'class': 'form-control'})

class ServicioForm(ModelForm):
    class Meta:
        model=Servicio
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        super(ServicioForm, self).__init__(*args, **kwargs)
        self.fields['nombre'].widget.attrs.update({'class': 'form-control'})   
        self.fields['descripcion'].widget.attrs.update({'class': 'form-control'})

class CategoriaForm(ModelForm):
    class Meta:
        model=Categoria
        fields = '__all__'

       
    def __init__(self, *args, **kwargs):
        super(CategoriaForm, self).__init__(*args, **kwargs)
        self.fields['nombre'].widget.attrs.update({'class': 'form-control'})   
        self.fields['estrellas'].widget.attrs.update({'class': 'form-control'})
        self.fields['servicios'].widget.attrs.update({'class': 'form-check-input form-check-label posicion-checkbox'})
        self.fields['servicios'].choices=[(c.pk,c.nombre) for c in Servicio.objects.all()]

    servicios = MultipleChoiceField(
         widget=CheckboxSelectMultiple,        
     )

class VendedorForm(ModelForm):
    email = EmailField(label='email')
    usuario = CharField(label='nombre de usuario')
    contrasenia = CharField(label='contraseña')
    email.widget.attrs.update({'class': 'form-control'})
    usuario.widget.attrs.update({'class': 'form-control'})
    contrasenia.widget.attrs.update({'class': 'form-control'})
    
    class Meta: 
        model = Persona
        fields = '__all__'
        exclude = [ 'usuario' ]
    
    def __init__(self, *args, **kwargs):
        super(VendedorForm, self).__init__(*args, **kwargs)
        self.fields['nombre'].widget.attrs.update({'class': 'form-control'})   
        self.fields['apellido'].widget.attrs.update({'class': 'form-control'})
        self.fields['documento'].widget.attrs.update({'class': 'form-control'})
        self.fields['tipo_documento'].widget.attrs.update({'class': 'form-control'})

#user_name, email, password

class EncargadoForm(ModelForm):
    clave = CharField(label='Clave')
    class Meta: 
        model = Persona
        fields = '__all__'
        exclude = [ 'usuario' ]

    def __init__(self, *args, **kwargs):
        super(EncargadoForm, self).__init__(*args, **kwargs)
        
        self.fields['nombre'].widget.attrs.update({'class': 'form-control'})   
        self.fields['apellido'].widget.attrs.update({'class': 'form-control'})
        self.fields['documento'].widget.attrs.update({'class': 'form-control'})
        self.fields['tipo_documento'].widget.attrs.update({'class': 'form-control'})
        self.fields['clave'].widget.attrs.update({'class': 'form-control'})

        
        
    
    


core/templates/core/clienteAdmin.html
{% extends 'base/base_administrador.html'%}
{% load static %}

{% block header %}
<button onclick="location.href='/core/homeAdministrador'" style="text-decoration:none"
    class="rounded-1 btn  btn-outline-secondary text-white ">Administrador:{% if administrador %}{{administrador.nombre}} {{administrador.apellido}}{% endif %}</button>
{% endblock header %}

{% block headerContenido %}
{% endblock headerContenido %}


{% block content %}

<center><h1 class="my-4">LISTADO DE CLIENTES</h1></center>


<!-- VISTA CLIENTES -->

<div class="formularioRegion" id="vistaClientes">

    <table id="example1" class="table table-striped table-bordered" style="width:100%">

        <thead>

            <tr>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Tipo</th>
                <th>Nro de Documento</th>
                <th>Puntos</th>
                <th>
                    <Center>ELIMINAR</Center>
                </th>
            </tr>
        </thead>
        <tbody>


            {% for cliente in colClientes %}
            <tr>

                <td> {{cliente.persona.nombre}}</td>
                <td> {{cliente.persona.apellido}}</td>
                <td> {{cliente.persona.get_tipo_documento_display}}</td>
                <td> {{cliente.persona.documento}}</td>
                <td> {{cliente.puntos}}</td>
                
                <td>
                    <center>
                        {% if cliente.bajaCliente %}
                        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#reciclarCliente"
                            onclick="abrir_modal('{% url 'core:modalReciclarCliente' cliente.pk %}','#reciclarCliente');"
                            title="Reciclar">
                            <i class="fas fa-recycle"></i>
                        </button>
                        {% else %}
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#eliminarCliente"
                            onclick="abrir_modal('{% url 'core:modalEliminarCliente' cliente.pk %}', '#eliminarCliente');" title="Eliminar">
                            <i class="fas fa-trash"></i>
                        </button>
                        {% endif %}
                    </center>

                </td>

            </tr>
            {% endfor %}

        </tbody>
        <tfoot>
            <tr>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Tipo</th>
                <th>Nro de Documento</th>
                <th>Puntos</th>
                <th>
                    <Center>ELIMINAR</Center>
                </th>
            </tr>
        </tfoot>
    </table>
    <!--Modal crear Encargado en otro html-->

    <div class="modal fade-scale" id="eliminarCliente" tabindex="-1" aria-labelledby="exampleModalLabel">
    </div>
    
    <div class="modal fade-scale" id="reciclarCliente" tabindex="-1" aria-labelledby="exampleModalLabel">
    </div>

</div>

{% endblock content %}

{% block extrajs %}

<script type="text/javascript">
    //SCRIPT DE DATATABLE
    const $ = jQuery.noConflict();
    $(document).ready(function () {
        $('#example1').DataTable();
    });</script>


{% endblock extrajs%}

core/templates/core/vendedor.html
{% extends 'base/base_administrador.html'%}
{% load static %}
{% block extra_css %}
<link rel="stylesheet" href="{% static '/css/vistaHotel.css' %}">
{% endblock extra_css %}
{% block header %}
<button onclick="location.href='/core/homeAdministrador'" style="text-decoration:none"
    class="rounded-1 btn  btn-outline-secondary text-white ">Administrador:{% if administrador %}{{administrador.nombre}} {{administrador.apellido}}{% endif %}</button>
{% endblock header %}

{% block headerContenido %}
{% endblock headerContenido %}


{% block content %}

<div class="switch-toggle switch-3 switch-candy sm row justify-content-center my-4">

    <input id="vendedor" name="state-d" radio type="radio"  value="vendedor" />
    <label for="vendedor" onclick='seleccionarEstado("vendedor")'>
        <h1>Vendedores</h1>
    </label>

    <input id="encargado" name="state-d" type="radio"  value="encargado" />
    <label for="encargado" onclick='seleccionarEstado("encargado")'>
        <h1>Encargados</h1>
    </label>
    <div id="effecto"></div>
    
 
    <style>
        .switch-toggle {
            margin-top: 1vh;
            flex-direction: row;

        }

        .switch-toggle input {
            position: absolute;
            opacity: 0;
            border-radius: 5px;
        }

        .switch-toggle input+label {
            padding: 20px;
            float: center;
            cursor: pointer;
        }
    </style>
</div>

<!-- VISTA VENDEDORES -->

<div class="formularioRegion" id="vistaVendedores">

    <table id="example1" class="table table-striped table-bordered" style="width:100%">

        <thead>

            <tr>
                <button type="button" class="btn btn-success ml-4 float-right btn-sm" data-toggle="modal"
                    data-target="#crearVendedor"
                    onclick="abrir_modal('{% url 'core:modalCrearVendedor' %}','#crearVendedor');">

                    <i class="fas fa-plus-circle"></i>
                    AÑADIR</button>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Tipo</th>
                <th>Nro de Documento</th>
                <th>
                    <Center>ACCIONES</Center>
                </th>
            </tr>
        </thead>
        <tbody>


            {% for vendedor in colVendedores %}

            
            <tr>

                <td> {{vendedor.persona.nombre}}</td>
                <td> {{vendedor.persona.apellido}}</td>
                <td> {{vendedor.persona.get_tipo_documento_display}}</td>
                <td> {{vendedor.persona.documento}}</td>

                <td>
                    <center>
                        {% if vendedor.estoyHabilitado %}
                        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#modificarVendedor"
                            onclick="abrir_modal('{% url 'core:modalModificarVendedor' vendedor.pk %}','#modificarVendedor');">
                            <i class="fas fa-edit"></i>
                        </button>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#eliminarVendedor"
                            onclick="abrir_modal('{% url 'core:modalEliminarVendedor' vendedor.pk %}', '#eliminarVendedor');" title="Eliminar">
                            <i class="fas fa-trash"></i>
                        </button>
                        {% else %}
                        
                        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#reciclarVendedor"
                            onclick="abrir_modal('{% url 'core:modalReciclarVendedor' vendedor.pk %}','#reciclarVendedor');" title="Reciclar">
                            <i class="fas fa-recycle"></i>
                        </button>
                        {% endif %}
                    </center>

                </td>

            </tr>
            
            {% endfor %}

        </tbody>
        <tfoot>
            <tr>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Tipo</th>
                <th>Nro de Documento</th>
                <th>
                    <Center>ACCIONES</Center>
                </th>

            </tr>
        </tfoot>
    </table>
    <!--Modal crear Servicio en otro html-->

    <div class="modal fade-scale" id="crearVendedor" tabindex="-1" aria-labelledby="exampleModalLabel">
    </div>
    <div class="modal fade-scale" id="modificarVendedor" tabindex="-1" aria-labelledby="exampleModalLabel">
    </div>
    <div class="modal fade-scale" id="eliminarVendedor" tabindex="-1" aria-labelledby="exampleModalLabel">
    </div>
    <div class="modal fade-scale" id="reciclarVendedor" tabindex="-1" aria-labelledby="exampleModalLabel">
    </div>

</div>

<!-- VISTA ENCARGADOS -->

<div class="formularioRegion" id="vistaEncargados">

    <table id="example2" class="table table-striped table-bordered" style="width:100%">

        <thead>

            <tr>
                <button type="button" class="btn btn-success ml-4 float-right btn-sm" data-toggle="modal"
                    data-target="#crearEncargado"
                    onclick="abrir_modal('{% url 'core:modalCrearEncargado' %}','#crearEncargado');">

                    <i class="fas fa-plus-circle"></i>
                    AÑADIR</button>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Tipo</th>
                <th>Nro de Documento</th>
                <th>Clave</th>
                <th>
                    <Center>ACCIONES</Center>
                </th>
            </tr>
        </thead>
        <tbody>


            {% for encargado in colEncargados %}
            
            <tr>

                <td> {{encargado.persona.nombre}}</td>
                <td> {{encargado.persona.apellido}}</td>
                <td> {{encargado.persona.get_tipo_documento_display}}</td>
                <td> {{encargado.persona.documento}}</td>
                <td> {{encargado.clave}}</td>

                <td>
                    <center>
                    {% if encargado.bajaEncargado %}
                        <button type="button" class="btn btn-success" data-toggle="modal"
                               data-target="#reciclarEncargado"
                               onclick="abrir_modal('{% url 'core:modalReciclarEncargado' encargado.pk %}','#reciclarEncargado');"
                               title="Reciclar">
                               <i class="fas fa-recycle"></i>
                        </button>
                    {% else %}
                            <button type="button" class="btn btn-danger" data-toggle="modal"
                            data-target="#eliminarEncargado"
                            onclick="abrir_modal('{% url 'core:modalEliminarEncargado' encargado.pk %}','#eliminarEncargado');"
                            title="Eliminar">
                            <i class="fas fa-trash"></i>
                            </button>
                            <button type="button" class="btn btn-warning" data-toggle="modal"
                            data-target="#modificarEncargado"
                            onclick="abrir_modal('{% url 'core:modalModificarEncargado' encargado.pk %}','#modificarEncargado');">
                            <i class="fas fa-edit"></i>
                            </button>
                    {% endif %}
                </center>
                </td>

            </tr>
            {% endfor %}

        </tbody>
        <tfoot>
            <tr>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Tipo</th>
                <th>Nro de Documento</th>
                <th>Clave</th>
                <th>
                    <Center>ACCIONES</Center>
                </th>

            </tr>
        </tfoot>
    </table>
    <!--Modal crear Encargado en otro html-->

    <div class="modal fade-scale" id="crearEncargado" tabindex="-1" aria-labelledby="exampleModalLabel">
    </div>
    <div class="modal fade-scale" id="modificarEncargado" tabindex="-1" aria-labelledby="exampleModalLabel">
    </div>
    <div class="modal fade-scale" id="eliminarEncargado" tabindex="-1" aria-labelledby="exampleModalLabel">
    </div>
    <div class="modal fade-scale" id="reciclarEncargado" tabindex="-1" aria-labelledby="exampleModalLabel">
    </div>

</div>



{% endblock content %}

{% block extrajs %}
<!-- const $ = jQuery.noConflict(); -->

<script type="text/javascript">
    //SCRIPT DE DATATABLE
    
    $(document).ready(function () {
        $('#example1').DataTable();
        $('#example2').DataTable();
    });</script>

<script>
    let state = sessionStorage.getItem("persona") || "vendedor";
    document.getElementById(state).setAttribute("checked" , "")
    mostrarListado(state)
    console.log(state)
    
    function seleccionarEstado(estado){
        sessionStorage.setItem("persona" , estado)
        document.getElementById(estado).setAttribute("checked" , "")
        mostrarListado(estado)
    }


    function mostrarListado(state){
        switch (state) {
            case "vendedor":
                document.getElementById("vistaEncargados").style.display = "none";
                document.getElementById("vistaVendedores").style.display = "block";
                break;
            case "encargado":
                document.getElementById("vistaEncargados").style.display = "block";
                document.getElementById("vistaVendedores").style.display = "none";
                break;
        }
    }

</script>

{% endblock extrajs%}